### ISSUE TITLE
Debian testing: problems with ESS 16.10-1 and R version 3.3.2

### ISSUE THREAD

**Issue by lbraglia** [emacs-ess/ESS#387] opened 2016-10-31 14:22 UTC
Hello everyone,

does anyone reported similar problems with ess 16.10-1 and  R version 3.3.2 RC?

These are the steps I do to reproduce it:
- Open any R script

- `C-c C-n` (or `C-c C-j`) on any line to start the interactive session

- the R process is started but it's hanging and emacs "freeze" (any command
is ignored)
```
 R version 3.3.2 RC (2016-10-23 r71578) -- "Sincere Pumpkin Patch"
 Copyright (C) 2016 The R Foundation for Statistical Computing
 Platform: x86_64-pc-linux-gnu (64-bit)

 R è un software libero ed è rilasciato SENZA ALCUNA GARANZIA.
 Siamo ben lieti se potrai redistribuirlo, ma sotto certe condizioni.
 Scrivi 'license()' o 'licence()' per dettagli su come distribuirlo.

 R è un progetto di collaborazione con molti contributi esterni.
 Scrivi 'contributors()' per maggiori informazioni e 'citation()'
 per sapere come citare R o i pacchetti di R nelle pubblicazioni.

 Scrivi 'demo()' per una dimostrazione, 'help()' per la guida in linea, o
 'help.start()' per l'help navigabile con browser HTML.
 Scrivi 'q()' per uscire da R.

!> > if(identical(getOption('pager'), file.path(R.home('bin'), 'pager'))) #
rather take the ESS one
```

The status bar says `ess-tracebug mode enabled` and the progress indicator continues to move in a circular way

Any hint? My best guess is some sort of Rv3.3.2 (updated this morning) - ESS interaction but not sure.

Best, Luca

**Comment by eddelbuettel** [comment] 2016-10-31 14:52
When I suggested on r-sig-debian that you come here I at least implicitly suggested you also consider previous (and hence now closed) issues.   Did you?

**Comment by lbraglia** [comment] 2016-10-31 15:20
Hi Dirk, 
since up to version 3.3.1 it worked without problems, so i've looked at recent (opened | closed) bugs (last 14 days to ceil weeks from 3.3.2 release) and didn't found anything pertinent (at least to my understanding).  
I'm sorry if I've missed some useful resources; any hint or pointer are very appreciated.

**Comment by eddelbuettel** [comment] 2016-10-31 15:38
Ok, I just did the following

1. Fired up a Docker instance of `r-base` knowing that it would be set to Debian testing
2. Ran `apt-get update`
3. Installed/updated ess and r-base core, getting me 16.10-1 and the 20161024 rc build of R 3.3.2.
4. Installed emacs.
5 Happily edited a script, using C-c C-n without issues.

This strikes me as non-reproducible.

**Comment by lbraglia** [comment] 2016-10-31 15:53
Thanks for your testing; the setup (at least for R and ess) is the same as mine.

BTW, in the meantime, I've found that with `C-g` one (I) can take the control of the buffers back (both editing and R process); so in some way or another emacs + ESS is still usable for interactive data analysis.

**Comment by lbraglia** [comment] 2016-10-31 16:10
I'll investigate a bit if the problem can be solved or at least if (with what) there are interactions (any hint appreciated).

In the meantime, this ticket can be closed for me.

**Comment by eddelbuettel** [comment] 2016-10-31 16:12
You can close it too.  Next time please do.

**Closed by eddelbuettel** 2016-10-31 16:12 UTC

**Comment by lbraglia** [comment] 2016-10-31 17:21
ok, i know, next time i'll do. I only wanted not to take unilateral decisions with the ticket since, formally, the issue is still there (despite being not reproducible, at least in a pristine environment).

**Comment by mmaechler** [comment] 2016-10-31 21:07
I agree that the issue may stay open, i.e., eventually be reopened. @eddelbuettel is right that we cannot do much as long as we can't reproduce the problem..  
OTHO @lbraglia is indeed seeing a problem that *is* new in ESS 16.10:  The above
>    if(identical(getOption('pager'), file.path(R.home('bin'), 'pager'))) # ....
line had been added by me to ESS but there should be a continuation to that `if(...)`  and I find it strange that that is *not* shown in your `*R*` console buffer... and so has probably *not* been sent (from ESS) to R.. and so R is waiting for the statement, i.e. function call, to be completed.

I find it strange indeed.
Martin

**Comment by lbraglia** [comment] 2016-11-01 06:33
I think it is as you suggested. After `# ...` i can insert R code if i command (say)
```
C-g a <- 1 ENTER
```
the if statement evaluation is terminated and i get the control of the R process.
Furthermore I tried to change `options('pager')` in `.Rprofile` to make that statement `TRUE` or `FALSE`, but that has had no impact on the behavior (which is the same)

**Comment by vspinu** [comment] 2016-11-01 09:33
The common cause of such problems is the customized R prompt. Make sure the prompt ends with "> " (space at the end).

**Comment by lbraglia** [comment] 2016-11-01 09:41
It already does. From `.Rprofile`
```
    "prompt" = "> ",
```
anyway i reproduced what above even commenting this `.Rprofile` line (so using standard R prompt, which is the same).

**Comment by eddelbuettel** [comment] 2016-11-01 20:56
FWIW I have another 'no problem' data point from my Ubuntu 16.04 laptop which by now has R 3.3.2 and ESS 16.10 -- and thanks to a hdmi connector wanted a fresh reboot so that I can be sure I am running these versions.   

All good here, and I do have a lot of other packages loaded too:

```r
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> > if(identical(getOption('pager'), file.path(R.home('bin'), 'pager'))) # rather take the ESS one
+       options(pager='cat')
> options(STERM='iESS', str.dendrogram.last="'", editor='emacsclient', show.error.locations=TRUE)
> a <- 2
> a
[1] 2
> 
```

Here the `a <- 2` was passed in via `C-c C-n` from a freshly created temp. file.

**Comment by rsuhada** [comment] 2016-12-11 22:24
Just to chime in: I have this problem with Ubuntu 15.10, ESS 16.10, R 3.2.2.
Same for the original poster [emacs stackexchange](https://emacs.stackexchange.com/questions/28382/ess-freezes-on-startup-with-ess-tracebug-mode-enabled) on Mac OS Sierra and R 3.3.1... Any help would be appreciated.

**Comment by lbraglia** [comment] 2017-02-06 11:32
@rsuhada can you test the devel version now, after #398 ?

**Comment by rsuhada** [comment] 2017-02-06 14:48
I'm on sabbatical without access to my Linux machine, I'll be back in 3 weeks... If still relevant by then I will check it. Thanks for pinging me!
