### ISSUE TITLE
Windows 7: ESS hangs when starting julia on "Cannot read history file c:/.../.juliahistory"

### ISSUE THREAD

**Issue by bwbell** [emacs-ess/ESS#162] opened 2015-04-20 18:04 UTC
Emacs version:  24.4.1
ESS version:     15.03
Julia version:     0.3.7

As described in issue #27, upon typing "M-x julia RET", emacs prints the message "Cannot read history file c:/.../.juliahistory" and hangs. 

Typing "C-g" unhangs emacs, and then one can type "C-x b _julia_ RET" to switch to the now running Julia buffer. However, that buffer does not display the julia prompt. (there is no cursor, no ">" sign, nothing to indicate when julia has finished running a command, or indeed that julia is actually running. 
![screenshot 2015-04-20 10 59 57-c](https://cloud.githubusercontent.com/assets/4262431/7236890/ad113e52-e74c-11e4-922b-45bca81e29fa.png)

**Comment by revereche** [comment] 2015-05-25 12:27
Also experiencing this issue, would appreciate some attention to it.

**Comment by ajsteven130** [comment] 2015-06-01 14:32
I can confirm this as well on Windows 7 with Emacs 24.5.1 and ESS 14.1.1

**Comment by vspinu** [comment] 2015-06-01 17:16
ESS cannot work without prompt. If this is configurable you should configure julia to send prompt, otherwise it sounds like a julia bug on windows. Does the prompt appear when you invoke julia from emacs shell?

**Comment by ajsteven130** [comment] 2015-06-02 08:22
There is no prompt (however the repl works) when Julia 0.3.8 is invoked in eshell on Emacs 24.5.1 on Windows 7. When powershell is used in emacs, it gives ERROR: prompt not defined. 

In both cmd and powershell using the native windows applications, the prompt works just fine.

For ESS, the prompt issue is, to me, a minor problem compared to the fact the Emacs hangs when julia is invoked from ESS.

Please let me know if there is any other information you could use. Alternatively, if you could provide some information about how the prompt should work, I can see about opening up an issue in the Julia Repo

**Comment by vspinu** [comment] 2015-06-02 08:46
> For ESS, the prompt issue is, to me, a minor problem compared to the fact the Emacs hangs when julia is invoked from ESS.

Missing prompt is the cause of the hang. Fixing the prompt will fix the cause. It's julia bug. If you can reproduce it  in emacs shell, please go ahead and report to julia folks.

> Alternatively, if you could provide some information about how the prompt should work,

The prompt just should be there as it is on non-Windows platforms and in Windows' cmd.

**Comment by adouzzy** [comment] 2015-06-11 03:01
I think it looked for the wrong file. Mine history file is called .julia_history not .juliahistory

**Comment by mmaechler** [comment] 2018-03-21 10:03
I propose to close this soon:
- it seems a julia bug (but julia will have advanced considerably since 2015)
- it is on a old version of Windows almost surely none of the maintainers can reproduce.

**Comment by nikoltoll** [comment] 2018-08-29 08:59
I still experience the bug with julia 1.0.0 on windows 7.

Running julia from an eshell results in a hang.

**Comment by habamax** [comment] 2018-08-29 09:05
The same is on win10 and julia 1.0.0

**Comment by jabranham** [comment] 2018-08-29 14:05
Can someone who experiences this check if #651 fixes the issue for you?

**Closed** 2018-08-29 14:28 UTC
Labels: lang:julia

**Comment by jabranham** [comment] 2018-08-29 14:36
Since that was merged, if you get ESS from MELPA it should (hopefully) be fixed in the next MELPA update, which usually takes between 1 and 6 hours.

**Comment by habamax** [comment] 2018-08-30 06:33
So the history file issue was solved (for me) but I still have to press `C-g`:

![image](https://user-images.githubusercontent.com/234774/44833678-84715a00-ac37-11e8-94a3-3cb8ee0a71a9.png)

**Comment by habamax** [comment] 2018-08-30 07:14
I have try to bisect the issue with debug messages and found out that it is `ess-wait-for-process` function hangs in the loop:

      (while (or (accept-process-output proc wait)
                 (unless (and sec-prompt (process-get proc 'sec-prompt))
                   (process-get proc 'busy)))
        (when force-redisplay
          (redisplay 'force))
        (when (> (- (float-time) start-time) .5)
          (setq wait .5)))


For me this part:

```
                 (unless (and sec-prompt (process-get proc 'sec-prompt))
                   (process-get proc 'busy))
```
is alway True.

**Comment by habamax** [comment] 2018-08-30 07:50
Looks like `process-get proc 'busy` never returns `nil`.

The only place I found it could be set up as `nil` is `inferior-ess-output-filter`. Which is never called when I start `M-x julia`.

I presume it should be called by a "callback" from within 
`(set-process-filter proc 'inferior-ess-output-filter)` but my knowledge is quite limited.

**Comment by vspinu** [comment] 2018-08-30 10:13
If you press C-g, do you see the end promt from julia? 

The busy state is reset once first prompt is detected. Looks like there is none in your case. 

I think there should be timeout there and the buffer should be shown immediately to the user. I will fix this before the release.

**Comment by habamax** [comment] 2018-08-30 10:50
If I press C-g, emacs just unhangs. Nothing happens in terms of prompts etc. Just the same window as before calling `M-x julia`.

But the julia process is running -- I can see it with list-processes.
![image](https://user-images.githubusercontent.com/234774/44847273-9b29a800-ac5b-11e8-97e5-f99b69ea170b.png)

**Comment by vspinu** [comment] 2018-08-30 22:15
There is a `*julia*` buffer somewhere in the background. You can switch to it and check for issues.

**Comment by chrchr** [comment] 2019-02-24 23:03
I am still experiencing this issue with ess 20190209.1549, Windows 10, Emacs 27.0.50. Can anyone confirm that it's working for them?

**Comment by jabranham** [comment] 2019-02-25 00:48
There's a bug in julia on Windows that prevents ESS from working. Long story short, julia on windows doesn't seem to print the prompt. #715 for more details.
