### ISSUE TITLE
display-buffer-alist reusable-frames does not work as expected

### ISSUE THREAD

**Issue by matsievskiysv** [emacs-ess/ESS#987] opened 2020-02-17 18:16 UTC
This was originally posted on [emacs so](https://emacs.stackexchange.com/q/55556/21814).

When using the `display-buffer-alist` value from [ess doc](https://github.com/emacs-ess/ESS/blob/master/doc/ess.texi#L632-L642)
```lisp
(setq display-buffer-alist
      '(("*R"
         (display-buffer-reuse-window display-buffer-pop-up-frame)
         (reusable-frames . 0))))
```
and starting R shell from some `ess-r-mode` buffer the following occurs: after creating a new frame displaying the R shell, Emacs displays a second instance of the `ess-r-mode` buffer in this new frame instead of returning to the old instance. 
Everything works correctly when I set `reusable-frames` globally
```lisp
(setq display-buffer-reuse-frames 0)
```
but this should not be necessary.

Quoting [so answer](https://emacs.stackexchange.com/a/55571/21814):

The erroneous behaviour happens only the first time one types `C-c C-z` (`ess-switch-to-inferior-or-script-buffer`) in an `ess-r-mode` buffer, i.e. before the corresponding inferior `*R*` process buffer has been created.

This is because `ess-force-buffer-current` calls `ess-request-a-process` with a non-`nil` `noswitch` argument when an inferior process does not already exist.

`ess-request-a-process`, in turn, does the following as its last step:
```lisp
(if noswitch
    (pop-to-buffer (current-buffer)) ;; VS: this is weird, but is necessary
  (pop-to-buffer (buffer-name (process-buffer (get-process proc)))))
```

This call to `(pop-to-buffer (current-buffer))` is wrong and is what causes your `ess-r-mode` buffer to appear a second time in the new frame. It was added in the following commit from 2012: <https://github.com/emacs-ess/ESS/commit/b29ea8f934f7c08a512c73f14e914bca7229b3c1>

I boldly say it is wrong because popping to the current buffer is quite an intrusive operation (as indicated by the bug in question), and the original intention of the author can almost definitely be written in a better way. I don't know what issue the author originally faced, but perhaps the ESS devs can figure it out.

**Comment by jabranham** [comment] 2020-02-20 22:47
Seems to work fine for me removing that call. You remember why it was necessary, @vspinu ? Here's the diff I'm working with, which includes some cleanup:

```diff
diff --git a/lisp/ess-inf.el b/lisp/ess-inf.el
index 3eccaa2c..449c57f8 100644
--- a/lisp/ess-inf.el
+++ b/lisp/ess-inf.el
@@ -731,22 +731,18 @@ Typically from a language-specific buffer, using LANGUAGE (and DIALECT)."
 (defun ess-request-a-process (message &optional noswitch ask-if-1)
   "Ask for a process, and make it the current ESS process.
 If there is exactly one process, only ask if ASK-IF-1 is non-nil.
-Also switches to the process buffer unless NOSWITCH is non-nil.  Interactively,
-NOSWITCH can be set by giving a prefix argument.
-Returns the name of the selected process."
-  (interactive
-   (list "Switch to which ESS process? " current-prefix-arg))
-                                        ; prefix sets 'noswitch
-  (ess-write-to-dribble-buffer "ess-request-a-process: {beginning}\n")
+Also switches to the process buffer unless NOSWITCH is non-nil.
+Interactively, NOSWITCH can be set by giving a prefix argument.
+Returns the name of the selected process. MESSAGE may be passed
+to `ess-completing-read'."
+  (interactive (list "Switch to which ESS process? " current-prefix-arg))
   (update-ess-process-name-list)
-
   (setq ess-dialect (or ess-dialect
                         (ess-completing-read
                          "Set `ess-dialect'"
                          (delete-dups (list "R" "S+" (or (bound-and-true-p S+-dialect-name) "S+")
                                             "stata" (or (bound-and-true-p STA-dialect-name) "stata")
-                                            "julia" "SAS" "XLS"  "ViSta")))))
-
+                                            "julia" "SAS")))))
   (let* ((pname-list (delq nil ;; keep only those matching dialect
                            (append
                             (mapcar (lambda (lproc)
@@ -762,54 +758,38 @@ Returns the name of the selected process."
                               (list ess-local-process-name)))))
          (num-processes (length pname-list))
          (auto-started?))
-    (if (or (= 0 num-processes)
-            (and (= 1 num-processes)
-                 (not (equal ess-dialect ;; don't auto connect if from different dialect
-                             (buffer-local-value
-                              'ess-dialect
-                              (process-buffer (get-process
-                                               (car pname-list))))))))
-        ;; try to start "the appropriate" process
-        (progn
-          (ess-write-to-dribble-buffer
-           (concat " ... request-a-process:\n  "
-                   (format
-                    "major mode %s; current buff: %s; ess-language: %s, ess-dialect: %s\n"
-                    major-mode (current-buffer) ess-language ess-dialect)))
-          (ess-start-process-specific ess-language ess-dialect)
-          (ess-write-to-dribble-buffer
-           (format "  ... request-a-process: buf=%s\n" (current-buffer)))
-          (setq num-processes 1
-                pname-list (car ess-process-name-list)
-                auto-started? t)))
+    (when (or (= 0 num-processes)
+              (and (= 1 num-processes)
+                   (not (equal ess-dialect ;; don't auto connect if from different dialect
+                               (buffer-local-value
+                                'ess-dialect
+                                (process-buffer (get-process
+                                                 (car pname-list))))))))
+      ;; try to start "the appropriate" process
+      (ess-start-process-specific ess-language ess-dialect)
+      (setq num-processes 1
+            pname-list (car ess-process-name-list)
+            auto-started? t))
     ;; now num-processes >= 1 :
     (let* ((proc-buffers (mapcar (lambda (lproc)
                                    (buffer-name (process-buffer (get-process lproc))))
                                  pname-list))
-           (proc
-            (if (or auto-started?
-                    (and (not ask-if-1) (= 1 num-processes)))
-                (progn
-                  (message "using process '%s'" (car proc-buffers))
-                  (car pname-list))
-              ;; else
-              (unless (and ess-current-process-name
-                           (get-process ess-current-process-name))
-                (setq ess-current-process-name nil))
-              (when message
-                (setq message (replace-regexp-in-string ": +\\'" "" message))) ;; <- why is this here??
-              ;; ask for buffer name not the *real* process name:
-              (let ((buf (ess-completing-read message (append proc-buffers (list "*new*")) nil t nil nil)))
-                (if (equal buf "*new*")
-                    (progn
-                      (ess-start-process-specific ess-language ess-dialect) ;; switches to proc-buff
-                      (caar ess-process-name-list))
-                  (process-name (get-buffer-process buf))
-                  ))
-              )))
-      (if noswitch
-          (pop-to-buffer (current-buffer)) ;; VS: this is weird, but is necessary
-        (pop-to-buffer (buffer-name (process-buffer (get-process proc)))))
+           (proc (if (or auto-started?
+                         (and (not ask-if-1) (= 1 num-processes)))
+                     (progn
+                       (message "Using process `%s'" (car proc-buffers))
+                       (car pname-list))
+                   ;; else
+                   (unless (and ess-current-process-name
+                                (get-process ess-current-process-name))
+                     (setq ess-current-process-name nil))
+                   ;; ask for buffer name not the *real* process name:
+                   (let ((buf (ess-completing-read message (append proc-buffers (list "*new*")) nil t nil nil)))
+                     (when (equal buf "*new*")
+                       (ess-start-process-specific ess-language ess-dialect) ;; switches to proc-buff
+                       (caar ess-process-name-list))))))
+      (unless noswitch
+        (pop-to-buffer (ess-get-process-buffer proc)))
       proc)))
 
 (defun ess-force-buffer-current (&optional prompt force no-autostart ask-if-1)

```

**Comment by vspinu** [comment] 2020-02-23 19:58
I don't recall why that was necessary. It was written long before the current emacs display buffer alist mechanism so definitely should be replaced as it's not longer relevant whatever the reason was. 

@jabranham let's go with your patch and test it out.

**Comment by jabranham** [comment] 2020-02-24 22:07
@seregaxvm I just pushed that commit; please let us know if you continue to experience this bug.

**Comment by seregaxvm** [comment] 2020-02-25 11:32
Behavior has changed. Now, when I start new R process from `ess-r-mode` buffer, two new frames with the same R repl buffer appear with the last one opened being active.

**Comment by jabranham** [comment] 2020-02-26 01:38
Interesting. Can you change `0` to `t` for reusable-frames and see if you still get that behavior?

**Comment by seregaxvm** [comment] 2020-02-26 17:14
> Can you change 0 to t for reusable-frames and see if you still get that behavior?

Same result.

Additionally, when I use this simplest `init.el` file:
```lisp
(package-initialize)
(add-to-list
 'package-archives
 '("melpa" . "http://melpa.milkbox.net/packages/")
 t)

(eval-when-compile
  (require 'use-package))

(use-package ess)
```
and run R repl from `ess-r-mode` buffer, emacs opens two R repl buffers - first in new buffer and second instead of `ess-r-mode` buffer. So I end up with two R repl buffers and no `ess-r-mode` buffer.

**Comment by jabranham** [comment] 2020-02-26 17:26
Well that sounds not good. I don't have access to ESS development now but
will confirm and revert when I can.

If someone beats me to it, feel free to revert that commit. I'll track this
issue down later.

**Comment by jabranham** [comment] 2020-02-26 22:33
Attempt #2 at #989.  All comments/thoughts/criticisms welcome.

@seregaxvm are you able to test it out from git?

**Comment by ywwry66** [comment] 2020-09-06 02:49
It seems #1040 only solves part of this issue. If I use C-c C-c from an R script, it works. However, if I use C-Ret, then it opens two new frames showing the inferior buffer, which is not the expected behavior.

**Comment by lionel-** [comment] 2020-09-06 06:06
Haven't looked in details yet, but this may be from https://github.com/emacs-ess/ESS/commit/be0850b23128508e33f0b0a58376660d6ef3e493.

@jabranham Is it correct to consult `ess-help-own-frame` for all evaluations instead of just help display? I would expect this variable to play no role in normal evaluations.

**Comment by ywwry66** [comment] 2020-09-07 01:50
Another question, is there any particular reason that you did not put `ess--with-no-pop-to-buffer` around the following line?
https://github.com/emacs-ess/ESS/blob/82cd308ae54a6b918bbceb235e6bf02f53e48e19/lisp/ess-inf.el#L773

**Comment by lionel-** [comment] 2020-09-07 06:21
I didn't see this start-process.

**Comment by jabranham** [comment] 2020-09-07 16:52
@lionel- We could additionally check if we're in a mode derived from ess-help-mode when checking those variables in those display-buffer statements.

**Comment by lionel-** [comment] 2021-03-26 16:53
> It seems #1040 only solves part of this issue. If I use C-c C-c from an R script, it works. However, if I use C-Ret, then it opens two new frames showing the inferior buffer, which is not the expected behavior.

I can't reproduce this. Is this still the case for you? If yes which Emacs version?

**Comment by lionel-** [comment] 2021-03-26 17:01
If I undo https://github.com/emacs-ess/ESS/commit/0ee75821d653ac362c72dbdb219b29244211118f I can reproduce! So it looks like this was fixed by @jabranham :)

**Closed by lionel-** 2021-03-26 17:01 UTC
Labels: process:windows
