### ISSUE TITLE
Unwanted buffer behaviour in case of R error

### ISSUE THREAD

**Issue by prosoitos** [emacs-ess/ESS#823] opened 2019-01-27 06:31 UTC
About 3ish months ago, my buffers and windows settings started to display a weird behaviour whenever R shows an error message:

I usually have 2 windows side by side, one with an ESS buffer for my R script and one with an iESS process and I send commands from the script to the inferior process with `ess-eval-paragraph-and-step` or `ess-eval-line-and-step`.

But now (started about 3+/- months ago), each time there is an R error, the ESS buffer gets replaced by the iESS buffer in its window (so that I end up with 2 iESS buffers side by side). My ESS buffer doesn't get killed and I can call it back into its window easily.

Also, for some types of R errors, things get even more crazy: once I recall my ESS buffer into its window, it is empty. I can restore its content simply with `undo`.

Finally, for some R errors, things get totally messed-up in the iESS buffer (the command which created the R error is still at the prompt, the point is further down and pressing `Enter` has no effect). Sometimes running `undo` in the iESS buffer saves it (usually several `undo` are necessary until I return to an empty prompt and then things are good again from there) and sometimes I have to kill the buffer altogether.

Things were working totally fine before and I did not change any setting when this started. Since it has now been a few months, nobody complained about this and the behaviour is not going back to normal, it has to be something in my settings... I would appreciate some help to figure out what it may be.

Of note, when I don't run into an R error, everything works normally in my ESS and iESS buffers.

Some info on my setup:

OS: Arch Linux (4.20.4-arch1-1-ARCH)
Window Manager: EXWM (with Xorg)
Emacs: GNU Emacs 26.1
ESS: latest Melpa version
R: version 3.5.2 (2018-12-20)

Thanks!

**Comment by jabranham** [comment] 2019-01-27 19:16
There was a change to how ESS displays buffers, but it shouldn't result in the behavior you're describing. Unfortunately, I don't experience this behavior. Is there a way to reproduce it reliably on your machine? If so, can you share that?

Do you have tracebug on? (it's on by default)

**Comment by prosoitos** [comment] 2019-01-27 20:30
The behaviours I described above are very reliable and happen every single time I hit an R error.

I am not sure about tracebug, but if it is on by default, I suspect so.

**Comment by prosoitos** [comment] 2019-01-27 20:34
Extremely simple situation:

I have my ESS buffer on the left window and the iESS buffer (fresh session) on the right. If I go to the iESS buffer and call a non existing object (say `a` for instance), the window expands to now occupy the full frame, and R sort of freezes like this:

![image](https://user-images.githubusercontent.com/4634851/51806544-e1e1f500-222f-11e9-8b62-29fdb737cc37.png)

I say "sort of freezes" because the cursor is still blinking and while pressing `Enter` doesn't work, I can save it by pressing `undo` until the faulty command gets deleted. From there on, things are normal again.

**Comment by prosoitos** [comment] 2019-01-27 20:36
Actually, I lied, in the above case, pressing `Enter` did work and produced this (often, it doesn't and undo is the only way out, or even, sometimes, killing the buffer altogether):

![image](https://user-images.githubusercontent.com/4634851/51806571-2ec5cb80-2230-11e9-94f6-5d45825d8173.png)

**Comment by prosoitos** [comment] 2019-01-27 20:39
In my normal workflow, I send commends from the ESS buffer to the iESS buffer. In this case, this is what happens:

My initial setup:

![image](https://user-images.githubusercontent.com/4634851/51806593-7ea49280-2230-11e9-9ff1-a563682519b2.png)

After I send the command `a` to the iESS, this is what it looks like:

![image](https://user-images.githubusercontent.com/4634851/51806600-9a0f9d80-2230-11e9-8081-f988a4a76804.png)

This happens totally reliably.

**Comment by prosoitos** [comment] 2019-01-27 20:45
As I mentioned, I never had this happen until an update a few months ago. Unfortunately, I do not remember precisely when as I was too busy to report the bug then and I was also hoping that it would get resolved by further updates.

Also, I don't hit R error at every command, so having to reset the windows, while quite frustrating, didn't happen enough to prevent me from working.

I did not change anything on my end when this started to happen.

**Comment by jabranham** [comment] 2019-01-27 21:55
Interesting. This definitely shouldn't happen. Do you have any customization for the display-buffer variables?

**Comment by prosoitos** [comment] 2019-01-27 23:58
I do. And is it very possible that my settings are a problem. I found the relevant help files quite confusing and did spend a lot of time playing with those settings until I got window and buffer behaviours which worked for me. Eventually they did though, until this thing here fell apart.

This is what I have:

```emacs-lisp
(setq display-buffer-alist
   (quote
    (("magit-diff.*"
      (display-buffer-reuse-window display-buffer-pop-up-window))
     ("\\*magit-.*-popup\\*" display-buffer-below-selected)
     ("\\*helm.*\\*"
      (display-buffer-reuse-window display-buffer-pop-up-window)))))
(setq display-buffer-base-action (quote (display-buffer-same-window)))

(setq display-buffer-reuse-frames t)

(setq display-buffer-function 'popwin:display-buffer)
```

**Comment by prosoitos** [comment] 2019-01-28 00:00
And I have no entry for ESS or iESS buffers in popwin, so that last one shouldn't have any effect.

**Comment by vspinu** [comment] 2019-01-28 11:09
Do you have the most recent ESS btw? There was a fix last week that should inhibit coverage of the current window by an iESS buffer. 

I think your `(setq display-buffer-base-action (quote (display-buffer-same-window)))` might be a culprit here. @jabranham will know better, but I think you essentially force all buffers (including `iESS`) to cover your current buffer. So, when we issue `pop-to-buffer` in our code you hijack that and essentially do `switch-to-buffer` instead.

**Comment by jabranham** [comment] 2019-01-28 13:47
@vspinu is right here. ESS began respecting `display-buffer` settings in late October. By specifying `display-buffer-base-action`, you're saying that you want all buffers to display in the same window. If that's really what you want, you can override the behavior for the inferior R buffers by modifying your setting of `buffer-display-alist`. I think just changing `magit-diff` so it matches `*R` buffers might get the behavior you want: `"\\(?:\\*R\\|magit-diff\\)"`. Can you try that and see if it works?

If it doesn't try commenting out all your display-buffer customizations and see if that does the trick.

**Comment by prosoitos** [comment] 2019-01-28 21:46
Ah! Late October sounds about right :slightly_smiling_face: So I guess that is what it is indeed. And that would explain why my settings worked before.

Funny: it is the second time I have a poor setting somewhere that was initially fine because ESS was not respecting it, then created issue when ESS started to respect it. Because of this, both times, I failed to pinpoint the source of the problem because I had set the particular setting many months before it started causing issue :slightly_smiling_face: 

@vspinu: I have the latest Melpa version. But I don't know whether new commits on Emacs packages which are on Melpa are pushed directly to the stable version or whether there is a development version, with only stable releases pushed to Melpa (with R packages and CRAN, all this is very clear to me. I know how to check a package version, how to install the devel version, etc. But the equivalent for Emacs packages and Melpa is confusing to me. I don't even know how to install a development version of an Emacs package, or a specific version, nor how to check the version of an installed package :confused: I guess I better do some homework and learn about this...).

Anyway, will try and let you know.

Thank you for your time!! Greatly appreciated! (and thank you for your work on ESS!).

**Comment by jabranham** [comment] 2019-01-28 21:52
@prosoitos Good to hear that it's all working out now. ESS is slowly becoming a more "modern" Emacs package, which means it should start to respect global configuration options like the display-buffer stuff.

MELPA serves the latest git commit from a package (with about a 4 to 8 hour lag because it takes the server some time to build). MELPA-stable is a separate package archive that serves the latest git tag (e.g. more like how CRAN works), but some Emacs packages don't have git tags so they aren't on it.

I'm closing this issue since I think it's "fixed." You mentioned something above though that evaluating a nonexistant object in R can hang the R process? I didn't totally understand that, if you still experience it please open a new issue.

**Comment by prosoitos** [comment] 2019-01-28 21:55
I removed my `display-buffer-base-action` and that totally solved the problem when I send a command from the ESS buffer to the iESS buffer.

So:

![image](https://user-images.githubusercontent.com/4634851/51868878-ee378200-2303-11e9-8a54-042c9b769fbf.png)

if I run `ess-eval-paragraph-and-step` becomes:

![image](https://user-images.githubusercontent.com/4634851/51868963-2212a780-2304-11e9-9b4d-a402c025a4ef.png)

as it should.

However, if I call `a` directly in the iESS buffer, I still have the same weird behaviour I described above:

![image](https://user-images.githubusercontent.com/4634851/51869010-42426680-2304-11e9-9e1b-e31921567cbc.png)

after pressing `Enter` in the iESS buffer becomes:

![image](https://user-images.githubusercontent.com/4634851/51869039-52f2dc80-2304-11e9-85a9-94a96201c19f.png)

and if I press `Enter` again:

![image](https://user-images.githubusercontent.com/4634851/51869064-600fcb80-2304-11e9-854e-0f936adfec40.png)

So it seems that there is something else going on.

**Comment by prosoitos** [comment] 2019-01-28 22:04
@jabranham: thank you very much for your explanations about Melpa.

I hadn't tried things yet when I first replied, but I now have (see above).

What still doesn't work (when I trigger an R error message by a command sent from within the iESS buffer) is very much what I was trying to explain: it isn't exactly that R hangs. But as you can see in the first picture, the error message doesn't show, nor does a new prompt. The point goes down and nothing happens in the iESS buffer. If I press `Enter` a second time, things become messed up. I often have to undo until I remove the faulty R command or relaunch the iESS process.

With this new info, do you want me to open a new issue on this as you suggest above?

**Comment by jabranham** [comment] 2019-01-28 22:21
@prosoitos thanks, I understand now. Looks like this is a small bug in ESS.

@vspinu this happens when `ess--flush-accumulated-output` gets called. The call to `display-buffer` triggers users display-buffer customizations, which we don't really need/want if the buffer is already selected. What do you think about this patch?

```patch
diff --git a/lisp/ess-tracebug.el b/lisp/ess-tracebug.el
index a0380b63..2108fa0d 100644
--- a/lisp/ess-tracebug.el
+++ b/lisp/ess-tracebug.el
@@ -1327,7 +1327,8 @@ prompts."
           (goto-char (point-min))
           (let ((case-fold-search nil))
             (when (re-search-forward "Error\\(:\\| +in\\)" nil t)
-              (display-buffer (process-buffer proc))))
+              (unless (equal (selected-window) (get-buffer-window pbuf))
+                (display-buffer (process-buffer proc)))))
           (goto-char (point-min))
           ;; First long + + in the output mirrors the sent input by the user and
           ;; is unnecessary in nowait case. A single + can be a continuation in
```

**Comment by prosoitos** [comment] 2019-01-28 23:03
Ah! Sorry: I was wrong about popwin having no setting affecting ESS:

As I posted earlier, I have:

```elisp
(setq display-buffer-function 'popwin:display-buffer)
```
And I actually have this in popwin:

```elisp
(setq popwin:special-display-config
   (quote
    (("\\*R:.*\\*" :regexp t :width 82 :stick t))))
```
This is the only way I have found to have the iESS buffer open in a window on the right of the ESS buffer.

**Comment by jabranham** [comment] 2019-01-28 23:06
@prosoitos No problem. You shouldn't need popwin anymore (at least, not for ess) now that we use `display-buffer`. Take a look at our manual `(info "(ess) Controlling buffer display")` and if there isn't an example there of how you want ESS to manage your buffers, let me know and I'll add one.

**Comment by prosoitos** [comment] 2019-01-28 23:21
Oh great! It was easy to adapt one of the examples to reproduce my popwin configuration. Your examples actually helped me understand `display-buffer-alist` (which I have found not very documented and quite obscure with my current elisp knowledge) a little better.

**Comment by prosoitos** [comment] 2019-01-29 00:09
Note: I still use popwin for my *R dired* buffers: I want them to pop-up at the top when I use them, which is rare. I haven't figured out how to do this with `display-buffer-alist`. But that's fine as popwin does the job very well.

Here is what it looks like when I call an *R dired* buffer:

![image](https://user-images.githubusercontent.com/4634851/51874747-12e92500-2317-11e9-9e0f-36a5dc99e8d4.png)

**Comment by jabranham** [comment] 2019-01-29 02:22
I think you'd have an entry that looks like this in `display-buffer-alist`:

```
("\\`\\*R dired"
 (display-buffer-reuse-window display-buffer-in-side-window)
 (side . top)
 (window-height . 0.50) ; means take up half the frame
 (reusable-frames . t))
```

let me know if that works for you.

**Comment by prosoitos** [comment] 2019-01-29 02:35
Actually, I am running into an issue with setting the iESS buffer with `display-buffer-alist`:

When I am in my usual ESS setting (ESS buffer left, iESS buffer right) and with the iESS buffer active, calling anything that will create a new new windows is blocked (so `helm-occur`, `helm-mini`, `split-window-and-jump`, etc.). I can do all of these from the ESS buffer and if the window configuration changes, then I can also do it from the iESS buffer. But not before then.

Since I had no issue with popwin, I may go back to setting it that way.

But your examples have really helped me understand `display-buffer-alist` and that will be really invaluable for other packages, even if I don't make use of it with ESS.

**Comment by prosoitos** [comment] 2019-01-29 03:08
> let me know if that works for you.

Since I decided to leave popwin still handle my ESS buffers, I won't try it. But you gave me the solution to my problem: I didn't realize that `display-buffer-in-side-window` could take a `side` argument with a value of `top`. So I knew how to put windows at the "bottom" and on the right and left "side", but not at the top.

Again, I have no doubt that this will be incredibly useful for some other window customization at some point as I have battled with this `display-buffer-alist` for a long time, with only limited success. So thank you!

**Closed** 2019-01-29 17:56 UTC

**Comment by prosoitos** [comment] 2019-01-30 06:14
Totally off topic, but I remember now why I had set `(setq display-buffer-base-action (quote (display-buffer-same-window)))`: it was to prevent dired from opening buffers in a jumping fashion as soon as there is more than one window in a frame. With that line, I could navigate up and down folder trees in dired while staying in the same window, without all this jumping back and forth to other window which I find totally crazy. I'll have to find another way to achieve that.

**Comment by prosoitos** [comment] 2019-01-30 07:56
```elisp
(setq same-window-buffer-names
   (quote
    ("(if (eq major-mode 'dired-mode) (buffer-name) nil)")))
```
has no effect :disappointed: 

And all my attempts at adding dired mode buffers to `display-buffer-alist` made EXWM crash.

**Comment by prosoitos** [comment] 2019-02-06 01:02
**edit:** Sorry @jabranham: I just realized that you had already answered this question higher up in this thread.

> By specifying `display-buffer-base-action`, you're saying that you want all buffers to display in the same window. If that's really what you want, you can override the behavior for the inferior R buffers by modifying your setting of `buffer-display-alist`. I think just changing `magit-diff` so it matches `*R` buffers might get the behavior you want: `"\\(?:\\*R\\|magit-diff\\)"`. Can you try that and see if it works?

I tried and it works like a charm. So I went back to `(setq display-buffer-base-action (quote (display-buffer-same-window)))`, which I really prefer for many things and adding `(quote (("*R" (display-buffer-reuse-window display-buffer-pop-up-window))))` to my `display-buffer-alist` works perfectly to prevent it in iESS buffer.

Thank you very much for all your time with this. It was extremely helpful.

**Comment by prosoitos** [comment] 2019-04-12 23:59
@jabranham: thank you again sincerely for all your time and help in this thread: popwin is unmaintained and now conflicts with Magit, so I had to migrate all my popwin settings to `display-buffer-alist`. The information you gave me here were incredibly useful and I would not have managed without them.

So, thank you!!!

**Comment by jabranham** [comment] 2019-04-13 01:21
Happy to help!
