### ISSUE TITLE
If `ess-eval-visibly` is  `'nowait`  ESS emits an extra newline

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#630] opened 2018-08-12 20:04 UTC
This has started happening ten days ago or so,.. but then I noticed it does not happen with everything set to default.

Today, I've started   `emacs -Q`,  loaded (the github version of) `ess/listp/ess-site.el`  and customized
`ess-eval-visibly` to `'nowait`  (default is `t`).

Then got to simple `q.R` buffer and send lines "down to" the  R  buffer.  It has often an extra newline after the  `>`  prompt.   That's quite undesirable.    I hope you can easily reproduce.

Martin

**Comment by lionel-** [comment] 2018-08-13 06:48
Another reprex at https://github.com/emacs-ess/ESS/issues/600#issuecomment-409203070

**Comment by mmaechler** [comment] 2018-08-13 07:03
;-) thank you for a really polite way to say that this is indeed a (succinct albeit) duplicate of #600

**Comment by lionel-** [comment] 2018-08-13 07:04
Not at all, I should have opened a new issue!

**Comment by mmaechler** [comment] 2018-08-21 13:34
It's not just when it `'nowait`  also when it is `nil`. 
This is  *really*  a  **BIG** pain!  As an R and package developer, I pay a lot of attention on how exactly print methods work.
A really minimal reprex is also this one:
```
emacs -Q -l ..../ess/lisp/ess-site.el --eval '(setq ess-eval-visibly nil)' -f R &
```
and then in the `*R*` buffer:

```{r}
> cat("fair. 123\n")
fair.
123
>
```
It took a while till I noticed this was the infamous ESS bug and not my (much more complicated) `cat()` statement that produced output in a loop.
So note that `ess-eval-visibly` has an effect in a situation where in the past it was **NEVER** used at all.
I have no R script file, just a simple R buffer aka "R console".  I really really hate that ESS does *anything* with R's output in such a situation !

**Comment by lionel-** [comment] 2018-08-21 13:37
This looks like a different bug.

**Comment by vspinu** [comment] 2018-08-21 18:55
Might be related. Likely our prompt regexp picks that as a prompt. I will check time permitting. 

> This is really a BIG pain! 

Martin. I think every single issue that you have ever opened had similar statement in it. It's just an extra new line in the output in a very specific context. How bad could it be? It has negative bug severity by any standard.

> I really really hate that ESS does anything with R's output in such a situation !

Well, if you want to have nice alignment of the output and prompts then you have to manipulate the output to some degree. These extra features come with tracebug filter, so the solution is simply to deactivate the tracebug.

**Comment by jabranham** [comment] 2018-08-21 21:02
@lionel-  I'm not sure it is a new/different bug. Try redefining this function this way and see if this and #600 are fixed:

```elisp
(defun ess--offset-output (prev-prompt str)
  (if prev-prompt
      (let* ((len (length prev-prompt))
             (last+ (eq (elt prev-prompt (- len 2)) ?+)))
        (if (and (> len 1) last+)
            ;; append > for aesthetic reasons
            (concat "> \n" str)
          str))
    str))
```

**Comment by mmaechler** [comment] 2018-08-22 08:01
Thanks a *lot* Alex,
for me , this solves this issue and also Lionel's reprex in #600.

I'm currently working with R code 90% of the  time (with the above change).
I will commit after a short while if I don't see anything suspicious.

Martin

**Comment by lionel-** [comment] 2018-08-22 08:16
> I will commit after a short while if I don't see anything suspicious.

This change likely breaks existing unit tests though. Maybe best let the authors of the code look into it?

**Comment by mmaechler** [comment] 2018-08-22 08:54
Sure... I'll hope you adopt it ... or something better

I would be happy to have a simple option that turns off manipulation of R output by emacs/ess entirely.

When I do not send any code via ESS/Emacs, but only start emacs, type `M-x R`  and continue typing in the `*R*` buffer, I'd really like an option where emacs/ess do *not* to interfere with R's output at all.
Yes, of course, I'm a special ESS user very often wanting to debug base R functions..
Is turning off ess-tracebug the only thing needed for such a behavior?

**Comment by lionel-** [comment] 2018-08-22 09:03
Agreed that it should be easy to disable this, if only for debugging purposes.

Also agreed that these issues are disruptive enough that they should be fixed before the release.

**Comment by vspinu** [comment] 2018-08-22 13:11
> Is turning off ess-tracebug the only thing needed for such a behavior?

Yes (at least it should be; will check). All the extra tweaks are in tracebug process filter.

Please don't commit on that code. I will fix this and other issues by the end of the day. There are several moving parts in there (one of them the comint itself) and there are at least one more issue with the new prompt behavior besides the two already mentioned here.

**Comment by lionel-** [comment] 2018-08-22 13:15
Here is another one, hopefully the same issue. With `ess-eval-function` and `'nowait` visibility:

```r
fn <- function() {
  1
  2
}
#> fn <- function() {
#> + > 
#>   1
#> + > 
#>   2
#> + > 
#> }
```

**Comment by jabranham** [comment] 2018-08-22 13:16
@lionel- that appears to be fixed with that change I suggested as well.

**Comment by jabranham** [comment] 2018-08-22 14:58
I haven't looked into this too much (and by that I mean at all, really), but I wonder how much of these kinds of problems (prompt detection) are caused by ESS overwriting comint's process filter. Has anyone looked into relying on e.g. `comint-preoutput-filter-functions` and friends rather than setting the process filter directly?

**Comment by vspinu** [comment] 2018-08-22 16:28
These are orthogonal. We are calling comint-filter as the final step. 

The main reason behind the current complexities in the evaluation code lies in the fact that we want to be able to accumulate incomplete input on repeated C-c C-c. If we could detect incomplete code on the emacs side a lot could be simplified. Particularly, `t` and `nowait` could be unified and ess-eval-linewise essentially m ade unnecessary.

**Comment by lionel-** [comment] 2018-08-22 16:35
On a related note, another application of detecting when an expression is complete is to evaluate paragraphs containing closing delimiters without sending those to the inferior. E.g. with cursor on the last line of that function, `ess-eval-paragraph` would just send the last two lines without the trailing `}`:

```r
fn <- function() {

  foo <- "foo"
  toupper(foo) <cursor>
}
```

**Comment by vspinu** [comment] 2018-08-22 16:52
Indeed. This is closely related to being able to send inner forms vs top forms discussion which we had before. 

I might be mistaken but I don't think such detection of forms is hard. No need for the complete parser here. Just jump out of paren constructs till the top level then extend the region by checking for continuation symbols. I am sure your indentation code already using such logic somewhere.

Let's aim to streamline this part for 19.04. For now I will just fix the offset code by allowing very small number of false negatives.

**Closed** 2018-08-22 22:58 UTC
Labels: bug, process:eval

**Comment by jabranham** [comment] 2018-08-23 13:30
Thanks @vspinu, that seems to fix it for me!

**Comment by lionel-** [comment] 2018-08-23 13:35
Seems to work great thanks!

Is it me or the `+` are now colourised as prompts and they weren't before? Looks great!

**Comment by jabranham** [comment] 2018-08-23 13:39
@lionel-  they've always been font-locked for me. Strange that they weren't for you.

Note that one consequence of this change is that if you enter `1 + ` at the prompt, we are also removing the `+ ` prompt output. I suppose that merits a new bug report though.

**Comment by lionel-** [comment] 2018-08-23 13:48
@jabranham looks like it's been the case for a couple of months but since the output was buggy I didn't notice.
