### ISSUE TITLE
julia mode hangs emacs

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#431] opened 2017-06-19 08:10 UTC
open a `.jl` file setting cursor to the first line of a function and sourcing that line will open an inferior julia buffer and source the line and my whole emacs session is unresponsive.
If i call `kill -s USR2 $emacspid` the current frame will close. 
Then I reopen the frame and have an `*ess-get-words*` buffer open together with the `*julia*` buffer and it is still not responsive.
Calling `kill -s USR2 $emacspid` again gives me the following traceback:
```
Debugger entered--Lisp error: (quit)
  accept-process-output(#<process julia> 0.5)
  ess-wait-for-process(#<process julia> nil nil nil)
  ess-command("pwd()\n" #<buffer  *ess-get-words*> sleep nil nil nil)
  ess-get-words-from-vector("pwd()\n")
  ess-synchronize-dirs()
  run-hooks(ess-idle-timer-functions)
  ess--idle-timer-function()
  apply(ess--idle-timer-function nil)
  timer-event-handler([t 0 1 0 repeat ess--idle-timer-function nil idle 0])
```
At this point emacs is responsive again and, but the julia buffer lost connection to its process.

When I start emacs without config (`emacs -q`) and load `julia-mode` and `ess` manually, then I only need one `kill -s USR2 $emacspid` to make the *ess-get-words* buffer appear and the traceback is the same.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv javascript helm auto-completion better-defaults
     (c-c++ :variables c-c++-enable-clang-support t)
     chrome ranger emacs-lisp ess
     (ess-extra :enabled-for ess)
     games git github haskell html
     (latex :variables TeX-view-program-selection
            '((output-pdf "PDF Tools"))
            TeX-view-program-list
            '(("PDF Tools" TeX-pdf-tools-sync-view))
            TeX-source-correlate-start-server t preview-scale-function 1.5)
     bibtex lua markdown octave
     (org :variables org-format-latex-options
          '(:foreground default :background default :scale 1.5 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers
                        ("begin" "$1" "$" "$$" "\\(" "\\[")))
     pdf-tools python
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     shell-scripts spell-checking syntax-checking themes-megapack version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by jabranham** [comment] 2018-09-22 16:29
I tried to reproduce this and couldn't. I opened a file `/tmp/test.jl`, the contents of which were:

```
function f(x,y)
           x + y
end
```

put point on the `f` in function, and did C-RET. 

I'm going to close this issue since it's a bit old and there have been many improvements to julia, Emacs, and ESS since it was originally reported. Please let me know if you still experience this though and I'll reopen it.

**Closed by jabranham** 2018-09-22 16:29 UTC
Labels: lang:julia
