### ISSUE TITLE
Add parent mode prog-mode

### ISSUE THREAD

**Issue by apnewberry** [emacs-ess/ESS#511] opened 2018-03-30 18:26 UTC
```
prog-mode is an interactive compiled Lisp function in ‘prog-mode.el’.

(prog-mode)

Major mode for editing programming language source code.

This mode runs the hook ‘prog-mode-hook’, as the final step
during initialization.
```

This is useful for setting up configuration for programming modes. For example `C-h f python-mode` says "Parent mode: ‘prog-mode’, which lets users set up keybindings etc that are nice in programming modes.

**Comment by izahn** [comment] 2018-03-30 18:38
Duplicate of https://github.com/emacs-ess/ESS/issues/219. Please do search before opening new issues.

**Comment by apnewberry** [comment] 2018-03-30 18:45
You're right, my apologies.

**Closed** 2018-03-30 18:45 UTC
