### ISSUE TITLE
company mode in ess mode not complete with new words

### ISSUE THREAD

**Issue by LuhengStat** [emacs-ess/ESS#565] opened 2018-06-11 01:46 UTC
I am using company mode to auto complete the words in ess mode.
I found that the words that newly defined without evaluated can not be 
completed. Such as
myword = 1
if I do not run that code into iess buffer, the word "myword" will not complete by company mode.
However, this feature does word in other mode, such python mode. I think 
maybe its the problem of ess mode.

**Comment by vspinu** [comment] 2018-06-11 12:56
>  I think maybe its the problem of ess mode.

Yes and no. ESS backends completes only those symbols which have been defined in the attached process. The problem is that company dispatches backends on prefix and not on missing completions. So, if ESS backend understands the prefix but doesn't complete, the ball is not passed further to other backends. See the [rationale](https://github.com/company-mode/company-mode/issues/142#issuecomment-46589054) behind this desing from the company's author.

I use `dabbrev-expand` (`M-/`) so I don't miss this completion. 

If you want to change the behavior you should group ESS backends with other backends which provided completion for contextual symbols (company-dabbrev-code, company-gtags, company-etags, company-keywords).  For example:

```el
;; don't auto-insert ess backends
(setq ess-use-company nil)

(defun my-ess-config ()
  (make-variable-buffer-local 'company-backends)
  (add-to-list 'company-backends
               '(company-R-args company-R-objects company-dabbrev-code :separate)))

(add-hook 'ess-mode-map #'my-ess-config)
```

Then go to a symbol and call `M-x company-diag` to see which backend completes at point.

**Comment by vspinu** [comment] 2018-06-11 13:00
BTW, `company-dabbrev-code` searches only the current buffer. If you want all buffers with the same mode then use `company-dabbrev` and set `company-dabbrev-other-buffers` to `t`.

**Comment by vspinu** [comment] 2018-06-11 13:02
I am closing this. If others think we should change the default behavior and include `company-dabbrev-code` along our backends please chime in.

**Closed by vspinu** 2018-06-11 13:02 UTC

**Comment by LuhengStat** [comment] 2018-06-13 02:49
Thanks. But the code do not work, and the error says (which is a little messing):

Warning (initialization): An error occurred while loading ‘/Users/wlh/.emacs’:

Wrong type argument: keymapp, (my-ess-config keymap (95) (menu-bar keymap (ESS menu-item ESS (keymap (Start Process Start Process keymap Start Process (Other menu-item Other (keymap Other (R-newest menu-item R-newest R-newest)))) ESS (What is this? (beta) menu-item What is this? (beta) ess-mouse-me) (Load file menu-item Load file ess-load-file) (Eval region | func | para menu-item Eval region | func | para ess-eval-region-or-function-or-paragraph) (Eval region | func | para & step menu-item Eval region | func | para & step ess-eval-region-or-function-or-paragraph-and-step) (Eval region | line menu-item Eval region | line ess-eval-region-or-line-and-step) (Enter expression menu-item Enter expression ess-execute) (nil menu-item ------) (Process menu-item Process (keymap Process (Goto end of process buffer menu-item Goto end of process buffer ess-switch-to-end-of-ESS) (Switch to process buffer menu-item Switch to process buffer ess-switch-to-inferior-or-script-buffer) (Switch Process menu-item Switch Process ess-switch-process) (Recreate R and S versions known to ESS menu-item Recreate R and S versions known to ESS menu-function-2 :key-sequence nil) (Start Process menu-item Start Process (keymap Start Process (R menu-item R R :help Start a new R process) (S menu-item S S :help Start a new S process) (Sqpe menu-item Sqpe Sqpe :enable ess-microsoft-p) (S+6-exisiting menu-item S+6-exisiting S+6-existing :enable ess-microsoft-p) (SAS menu-item SAS SAS-menu) (Other menu-item Other (keymap Other (No other R or Sqpe versions menu-item No other R or Sqpe versions nil :enable (quote nil)))) (About menu-item About menu-function-5 :key-sequence nil))) (Eval visibly  menu-item Eval visibly  nil :filter #[257 \302\301!\300"\207 [Eval visibly  ess--generate-eval-visibly-submenu easy-menu-filter-return] 4 

(fn MENU)]))) (nil-8 menu-item ------) (ESS Eval menu-item ESS Eval (keymap ESS Eval (Eval region | func | para menu-item Eval region | func | para ess-eval-region-or-function-or-paragraph) (Eval region | func | para & step menu-item Eval region | func | para & step ess-eval-region-or-function-or-paragraph-and-step) (Eval region | line menu-item Eval region | line ess-eval-region-or-line-and-step) (nil menu-item -----) (Eval buffer menu-item Eval buffer ess-eval-buffer) (Eval buffer till here menu-item Eval buffer till here ess-eval-buffer-from-beg-to-here) (Eval buffer from here menu-item Eval buffer from here ess-eval-buffer-from-here-to-end) (Eval region menu-item Eval region ess-eval-region) (Eval function menu-item Eval function ess-eval-function) (Eval line menu-item Eval line ess-eval-line) (Eval line & step menu-item Eval line & step ess-eval-line-and-step) (Eval paragraph menu-item Eval paragraph ess-eval-paragraph) (Eval paragraph & step menu-item Eval paragraph & step ess-eval-paragraph-and-step) (Eval chunk menu-item Eval chunk ess-eval-chunk :enable ess-noweb-mode) (Eval chunk and step menu-item Eval chunk and step ess-eval-chunk-and-step :enable ess-noweb-mode) (Eval thread menu-item Eval thread ess-eval-thread :enable ess-noweb-mode) (About menu-item About menu-function-6 :key-sequence nil))) (Eval and Go menu-item Eval and Go (keymap Eval and Go (Eval buffer menu-item Eval buffer ess-eval-buffer-and-go) (Eval region menu-item Eval region ess-eval-region-and-go) (Eval function menu-item Eval function ess-eval-function-and-go) (Eval line menu-item Eval line ess-eval-line-and-go) (Eval paragraph menu-item Eval paragraph ess-eval-paragraph-and-go) (Eval chunk menu-item Eval chunk ess-eval-chunk-and-go :enable ess-noweb-mode) (Eval thread menu-item Eval thread ess-eval-thread-and-go :enable ess-noweb-mode) (About menu-item About menu-function-6 :key-sequence nil))) (Motion menu-item Motion (keymap Motion (Beginning of function or para menu-item Beginning of function or para ess-goto-beginning-of-function-or-para) (End of function or para menu-item End of function or para ess-goto-end-of-function-or-para) (nil menu-item -----) (Backward list menu-item Backward list backward-list) (Forward list menu-item Forward list forward-list) (Next parenthesis menu-item Next parenthesis down-list) (Enclosing parenthesis menu-item Enclosing parenthesis backward-up-list) (Backward sexp menu-item Backward sexp backward-sexp) (Forward sexp menu-item Forward sexp forward-sexp) (About menu-item About menu-function-7 :key-sequence nil))) (ESS Edit menu-item ESS Edit (keymap ESS Edit (Edit new object menu-item Edit new object ess-dump-object-into-edit-buffer) (Complete Filename menu-item Complete Filename comint-replace-by-expanded-filename) (Complete File or Object menu-item Complete File or Object ess-indent-or-complete) (Kill sexp menu-item Kill sexp kill-sexp) (Mark function menu-item Mark function ess-mark-function-or-para) (Indent expression menu-item Indent expression ess-indent-exp) (Indent line menu-item Indent line ess-indent-command) (Toggle Auto-Fill Mode menu-item Toggle Auto-Fill Mode auto-fill-mode) (Undo menu-item Undo undo) (About menu-item About menu-function-8 :key-sequence nil))) (nil-13 menu-item ------) (start-dev) (Roxygen menu-item Roxygen (keymap Roxygen (Update/Generate Template menu-item Update/Generate Template ess-roxy-update-entry) (Preview Rd menu-item Preview Rd ess-roxy-preview-Rd) (Preview HTML menu-item Preview HTML ess-roxy-preview-HTML) (Preview text menu-item Preview text ess-roxy-preview-text) (Hide all menu-item Hide all ess-roxy-hide-all) (Toggle Roxygen Prefix menu-item Toggle Roxygen Prefix ess-roxy-toggle-roxy-region)) :visible (and ess-dialect (string-match ^R ess-dialect))) (Package development menu-item Package development (keymap Package development (Active? menu-item Active? ess-r-package-mode :button (:toggle . ess-r-package-mode)) (Select package for evaluation menu-item Select package for evaluation ess-r-set-evaluation-env)) :visible (and ess-dialect (string-match ^R ess-dialect))) (Tracebug menu-item Tracebug (keymap Tracebug (Active? menu-item Active? ess-toggle-tracebug :button (:toggle or (and (ess-process-live-p) (ess-process-get (quote tracebug))) ess-use-tracebug)) (Show traceback menu-item Show traceback ess-show-traceback :enable (ess-process-live-p)) (Show call stack menu-item Show call stack ess-show-call-stack :enable (ess-process-live-p)) (Watch menu-item Watch ess-watch :enable (and (ess-process-live-p) (ess-process-get (quote tracebug)))) (Error action cycle menu-item Error action cycle ess-debug-toggle-error-action :enable (and (ess-process-live-p) (ess-process-get (quote tracebug)))) (nil menu-item ----) (Flag for debugging menu-item Flag for debugging ess-debug-flag-for-debugging :enable ess-local-process-name) (Unflag for debugging menu-item Unflag for debugging ess-debug-unflag-for-debugging :enable ess-local-process-name) (nil-8 menu-item ----) (Set BP menu-item Set BP ess-bp-set) (Set conditional BP menu-item Set conditional BP ess-bp-set-conditional) (Set logger BP menu-item Set logger BP ess-bp-set-logger) (Kill BP menu-item Kill BP ess-bp-kill) (Kill all BPs menu-item Kill all BPs ess-bp-kill-all) (Next BP menu-item Next BP ess-bp-next) (Previous BP menu-item Previous BP ess-bp-previous) (nil-16 menu-item -----) (About menu-item About ess-tracebug-show-help)) :visible (and ess-dialect (string-match ^R ess-dialect))) (end-dev) (nil-16 menu-item ------) (Font Lock menu-item Font Lock nil :filter #[257 \302\301!\300"\207 [Font Lock ess--generate-font-lock-submenu easy-menu-filter-return] 4 

(fn MENU)] :enable ess-font-lock-keywords) (nil-18 menu-item ------) (Describe menu-item Describe describe-mode) (About editing menu-item About editing menu-function-10 :key-sequence nil) (Read ESS info menu-item Read ESS info menu-function-11 :key-sequence nil) (Send bug report menu-item Send bug report ess-submit-bug-report)))) (44 . ess-smart-comma) (9 . ess-indent-or-complete) (125 . ess-electric-brace) (123 . ess-electric-brace) (24 keymap (110 keymap (102 . ess-narrow-to-defun-or-para) (100 . ess-narrow-to-defun-or-para))) (C-return . ess-eval-region-or-line-and-step) (27 keymap (106 . ess-indent-new-comment-line) (10 . ess-indent-new-comment-line) (13 . ess-use-this-dir) (8 . ess-mark-function-or-para) (17 . ess-indent-exp) (63 . ess-list-object-completions) (5 . ess-goto-end-of-function-or-para) (1 . ess-goto-beginning-of-function-or-para) (24 . ess-eval-region-or-function-or-paragraph)) (3 keymap (20 . ess-dev-map) (5 . ess-extra-map) (4 . ess-doc-map) (17 . ess-quit) (126 . ess-show-call-stack) (96 . ess-show-traceback) (11 . ess-force-buffer-current) (9 . ess-complete-object-name-deprecated) (19 . ess-switch-process) (22 . ess-display-help-on-object) (12 . ess-load-file) (26 . ess-switch-to-inferior-or-script-buffer) (25 . ess-switch-to-ESS-deprecated) (10 . ess-eval-line) (14 . ess-eval-line-and-step) (16 . ess-eval-paragraph-and-step) (3 . ess-eval-region-or-function-or-paragraph-and-step) (6 . ess-eval-function) (C-down . ess-eval-buffer-from-here-to-end) (C-up . ess-eval-buffer-from-beg-to-here) (2 . ess-eval-buffer) (27 keymap (108 . ess-load-file) (106 . ess-eval-line-and-go) (112 . ess-eval-paragraph-and-go) (102 . ess-eval-function-and-go) (98 . ess-eval-buffer-and-go) (114 . ess-eval-region-and-go)) (18 . ess-eval-region)) (remap keymap (yank . ess-yank)) (13 . ess-newline-and-indent))

**Comment by vspinu** [comment] 2018-06-13 10:18
Sorry. I made a typo:

```el
(add-hook 'ess-mode-hook #'my-ess-config)
```

**Comment by LuhengStat** [comment] 2018-06-13 12:01
Thanks. I use this settings and the company mode still not find the newly defined word such as 
`
mytestword = 1
`
If I write "myte", but the company words not shown up. However, I could complete this with M-/ command. Do you know how to add the newly written words to the company backends?

**Comment by vspinu** [comment] 2018-06-13 22:34
It works fine for me. Try `company-diag` to investigate what's going on.

**Comment by vspinu** [comment] 2018-06-14 12:06
I think I know what's going on.  Current mode should inherit from `prog-mode` in order for `company-dabbrev-code` to work. ESS inherits from prog-mode only in the development version. 

Either upgrade to a development version, or try adding `ess-mode` to `company-dabbrev-code-modes`:

```el
(add-to-list 'company-dabbrev-code-modes 'ess-mode)
```

**Comment by LuhengStat** [comment] 2018-06-14 13:08
Great, it works. Thanks.

**Comment by Xunius** [comment] 2020-02-10 15:13
I noticed something similar in python-mode:
In my script I have
```
mytestvar = 10
```
My `company-complete` finds it only after that line, but not before it.
Calling `M-/` finds it though.

Here is the `company-dabbrev-code-modes` value output:
```
company-dabbrev-code-modes is a variable defined in ‘company-dabbrev-code.el’.
Its value is
(prog-mode batch-file-mode csharp-mode css-mode erlang-mode haskell-mode jde-mode lua-mode python-mode)
```

I'm very new to emacs so I might miss something, please help.
