### ISSUE TITLE
ESS Julia eldoc feature not working

### ISSUE THREAD

**Issue by my-little-repository** [emacs-ess/ESS#441] opened 2017-07-18 18:39 UTC
I just downloaded julia-mode and ESS (ess-version: 16.10-1 [elpa: 20170710.118]) from MELPA and neither completion nor eldoc work. 

When `ess-eldoc-show-on-symbol` is true and I  type the word `map` at the *julia* repl, eldoc reports the following error. 

     eldoc error: (wrong-type-argument sequencep map) 

I browsed ESS source and I can't make sense of the code defining the function `ess-julia-eldoc-function` in the  file `ess-julia.el`, see https://github.com/emacs-ess/ESS/blob/master/lisp/ess-julia.el#L259. The local variable funname is first set at the value given by `(ess-symbol-at-point)` which returns a symbol. Then the length of the symbol is computed. Symbols do not have length, hence the error.

This is on GNU Emacs 25.1.1 of 2017-04-23.

**Comment by cszang** [comment] 2017-07-19 08:15
Same problem here. I tried with both ESS 16.10-1 from MELPA and current ESS git HEAD (064174931f0cbf91ad24fda883909a06eee10f6e), also with emacs -Q and fresh installs of ESS and company. 

Confirmed for both Emacs 25.2.1 and 25.1.1. ESS works just perfect with R with both company and auto-complete.

**Comment by vspinu** [comment] 2017-07-19 10:36
Folks, we are tired of tracking julia's changes. Mostly because none of us is actively using julia. Please have a look at [ESS module](https://github.com/emacs-ess/ESS/blob/master/etc/ess-julia.jl#L1) see what is broken and change whatever you see fit (preferably backward compatible). We would be more than happy to accept any PRs on this. ESS module is close to trivial, anyone with even basic julia knowledge should be able to figure it out.

**Comment by cszang** [comment] 2017-07-19 10:38
Fair enough, thanks.

**Comment by vspinu** [comment] 2017-07-20 07:45
Fixed by @nverno in #442 .

**Closed by vspinu** 2017-07-20 07:45 UTC
