### ISSUE TITLE
Auto-complete quick help writes directly in iESS buffer

### ISSUE THREAD

**Issue by idiot-z** [emacs-ess/ESS#846] opened 2019-02-21 12:13 UTC
Hello,
ac quick help works fine with function parameters (see screenshots 1&2)
![screenshot_1](https://user-images.githubusercontent.com/6696194/53167831-675f8780-35d9-11e9-840f-438f7bfab137.png)
![screenshot_2](https://user-images.githubusercontent.com/6696194/53167842-721a1c80-35d9-11e9-8a8d-c0e05afddeea.png)
However for anything else it writes the help content directly in the iESS buffer (screenshots 3&4)
![screenshot_3](https://user-images.githubusercontent.com/6696194/53167905-9ece3400-35d9-11e9-92e6-bd0006989be0.png)
![screenshot_4](https://user-images.githubusercontent.com/6696194/53167916-a261bb00-35d9-11e9-8384-fd0256623847.png)
This is very annoying because it erases the previously written command and if not careful one can execute the whole help file.
I am running emacs 26.1-2 on archlinux, with ess 20190220.2125 and auto-complete 20170125.245 from melpa, with default configurations.
I have found similar issues ([https://github.com/emacs-ess/ESS/issues/109](https://github.com/emacs-ess/ESS/issues/109), [https://stackoverflow.com/questions/27018075/strange-no-documentation-error-in-ess](https://stackoverflow.com/questions/27018075/strange-no-documentation-error-in-ess), [https://stat.ethz.ch/pipermail/ess-help/2013-August/009288.html](https://stat.ethz.ch/pipermail/ess-help/2013-August/009288.html)) but couldn't find an answer.
Can anyone help?
Thank you very much.

Edit: setting `(setq ac-use-quick-help nil)` helps, but I'd still like to be able to use the quick help.

**Comment by jabranham** [comment] 2019-02-21 15:10
Duplicate of #842 I think.

Long story short is that auto-complete is unmaintained upstream. None of the ESS developers use auto-complete, so a fix is pretty low-priority. Patches are, of course, welcome. Company-mode is the more modern alternative, we're encouraging auto-complete users to switch to company.

**Closed by jabranham** 2019-02-21 15:10 UTC

**Comment by idiot-z** [comment] 2019-02-21 15:51
Alright, thanks. I'll switch to company.
