### ISSUE TITLE
indentation -- if .. else if ..  with and without `{ .. }`

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#265] opened 2015-11-03 15:27 UTC
An excerpt from an R package source (from someone else) which I'm editing:
```{r}
{
    if (ncol(x) != 2)
        stop("'x' must be 2-dimensional")

    fillbox <- TRUE
    if (length(col) == 0)
        col <- c("skyblue", "red", "red4")
    else if (length(col) == 1) {
        col <- rep.int(col, 3)
        fillbox <- FALSE
    }
  else if (length(col) == 2)
      col <- rep(col, 1:2)
  else if (length(col) > 3)
    col <- col[1:3]

    if (length(pch) == 0)
        pch <- c(1, 16)
    else if (length(pch) == 1)
        pch <- c(pch, 16)
    else if (length(pch) > 2)
        pch <- pch[1:2]
}
```
Note that some of the `else if(..) ....`  are not indented enough.
Our algorithm is tripped up because it seems to assume that  `{ .. }` is used either always or never...
an assumption that is clearly wrong.

An even more typical code excerpt would be
```{r}
{
   if(something)
      stop("something")
else { 
       line1
       line2
   }
}
```
which also tends to indent the `else {` line wrongly

**Comment by lionel-** [comment] 2015-11-03 15:49
> Our algorithm is tripped up because it seems to assume that { .. } is used either always or never...

nope, it's because a broken else (with a newline after the closing brace) doesn't get indented. It stays in place. I'll look into it.

> which also tends to indent the else { line wrongly

I don't see it. What is wrong here?

**Comment by mmaechler** [comment] 2015-11-03 15:52
I've (manually) updated the 2nd code snippet to what I *sometimes* have seen the last couple of days
(when I started editing very badly formatted R code of someone else, and use C-M-q  etc to get it into shape).

**Comment by lionel-** [comment] 2015-11-03 16:00
I don't use `C-M-q`, I use `vap=` (vim user here ;))

But apparently C-M-q only indents the sexp following point, not the entire R expression. Is it possible your problem stems from this? And what is it exactly? In your snippet I can only see that `stop()` is not indented enough, but if you try to indent that line it works correctly.

Should I update `(ess-indent-exp)` so that the entire R expression surrounding point gets indented? It'd be easy to do.

**Closed** 2015-11-03 16:06 UTC

**Comment by mmaechler** [comment] 2015-11-03 17:14
Sorry for being slow:  "Of course"  I use  C-M-q at the top-level opening `{`...
and only then it should indent everything...
Note that this is not just ESS, this is a general Emacs feature / behavior, e.g., also in C, lisp,..

**Comment by lionel-** [comment] 2015-11-03 17:25
ok, I can't reproduce so I guess it's fixed by my patch

**Comment by vspinu** [comment] 2015-11-03 21:53
> Should I update (ess-indent-exp) so that the entire R expression surrounding point gets indented? It'd be easy to do.

I think it should inent next sexp. Currently it does so if the point is followed by `(` or `{` but not before function calls like with`|foo( ...`. This is incredibly annoying as you need to navigate to open `(` before each `C-M-q`. So if it's easy to fix please do that. Thanks.

**Comment by lionel-** [comment] 2015-11-04 00:11
should it indent continuations as well or just calls?

**Comment by vspinu** [comment] 2015-11-04 16:19
Sure. That makes a lot of sense. I would prersonaly prefer it to indent the whole current syntactic block starting from level 0. Currently one needs to select it or navigate to block's beginning and only then indent.

**Comment by lionel-** [comment] 2015-11-04 16:34
so it's not the syntactic unit following point but the one surrounding point?

btw, how about calling a syntactic unit a "statement". I guess it's better to call them "expression" but at the moment ess-r-syntax.el uses this term to refer to objects, blocks and calls (without continuations).

Does it make sense to consider expressions containing operators as statements?

**Comment by vspinu** [comment] 2015-11-04 18:14
> so it's not the syntactic unit following point but the one surrounding point?

Well. That would be my preference. It's very little that can go wrong IMO. Martin, any reservations on your side? 

> Does it make sense to consider expressions containing operators as statements?

I would retain using this word at all. As many thing in C/C++ word the notion is confusing and it's essentially comes down to whether a piece of code returns a value or not. Everything in R returns a values so there is no much point calling them statements. 

Using our own definition of statemet is confusing. I think it would be nicer to refactor ess-r-syntax.el into better naming.

**Comment by mmaechler** [comment] 2015-11-04 19:51
Well, I'm lost about the details of what you are talking about.  I've used   C-M-q  mostly after putting point on an opening "{" ... and expect the same behavior as in C / C++ in such a case.

Apropos "statement": You are right @vspinu about the distinction of R and C, as in R everything is a function call.  So  "function call" is more precise than "statement".  OTOH, I don't think statement can be misunderstood also for R.  As in C,  'statements' / "function call"s  can be nested and the problem may be more about the correct nesting level than a distinction between "statement" and "function call", no?

**Comment by lionel-** [comment] 2015-11-04 20:45
> So "function call" is more precise than "statement".

Yes but if we call `a + b` a function call it becomes very hard to reason about the syntax. We have to give different names to different syntax usages. Right now only expressions of the type `symbol()` and `symbol[]` are considered calls in ess-r-syntax.el.


> Using our own definition of statemet is confusing. I think it would be nicer to refactor ess-r-syntax.el into better naming.

So basically everything is an expression, which is not good for our purposes. How about `clause` and `sentence`? A clause is "a unit of grammatical organization next below the sentence in rank and in traditional grammar said to consist of a subject and predicate". It somehow fits.

The sentence would be the largest syntactic unit, and a clause would be either an object, a call or a block. Then we have `infix-expression` when an operator is involved. So `a + b` and ` {stuff} + a + b` are both a sentence and an infix expression. And `call({stuff} + a + b)` is a sentence but not an infix expression (though it contains one).

I think sentence is good, clause a bit less and we could probably find better. I'm not sure it's possible to find the perfect names that completely fit what we try to describe though.

The reason we need a name for "clauses" is because the syntax tools have no notion of operator precedence. When we climb a continuation, we climb sequentially from one clause to the other, given that clauses are separated by operators. Thus, clauses are never infix expressions. Also, the difference between an infix expression and a continuation is that the former is made of one operator, and two expressions (both of which can be another infix expression), while the latter is made of one or many operators, and two or more "clauses", that is, expressions that are never infixed.

Precision and consistence are hard!

**Comment by lionel-** [comment] 2015-11-04 20:49
> I would prersonaly prefer it to indent the whole current syntactic block starting from level 0.

I see that in elisp, C-M-q indents following point. I think it would make more sense to have context-indentation with C-u C-M-q.

**Comment by lionel-** [comment] 2015-11-05 13:04
Here you go: https://github.com/emacs-ess/ESS/commit/36b9e387ab1c942b116425c4b73ea3cd72390d2e

**Comment by lionel-** [comment] 2015-11-05 16:20
about the naming issue, I still think "statement" is better than "sentence".

>  As many thing in C/C++ word the notion is confusing and it's essentially comes down to whether a piece of code returns a value or not.

There's still a bit of this idea in the concept here. The return value of a R statement (or sentence...) is wasted most of the time except when it's the last one of a block. All other statements are only useful for their side effects (local assignment, etc).

So I think statement is the least confusing and most natural of all choices here.

As for clauses, we can simply call them prefixed-expressions. `prexpr` for short?
