### ISSUE TITLE
repeated C-M-a/e don't move cursor to previous/next function

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#251] opened 2015-10-05 09:42 UTC
Reported in this [thread](https://stat.ethz.ch/pipermail/ess-help/2015-October/thread.html#10764)

There are two difficulties with fixing this. First is that `ess-end-of-function` relies on `ess-beginning-of-function`.  Second, the semantics of `-or-paragraph` navigation should be meaningfully preserved.

**Comment by lionel-** [comment] 2015-10-05 10:30
I think we need to have one defun motion that has strict behaviour. That could be `(ess-beginning-of-function)`. In this case, it should not move beyond the current function at point, and all motion sugar like moving to the next function should be handled in the `-or-paragraph` variant.

**Comment by vspinu** [comment] 2015-10-05 10:38
In elisp and C/Java `beginning-of-defun` finds previous function even when point is at the start of a function. I think we need to comply.  

For the evaluation purpose we need to have a separate abstraction that would be more restrictive. Maybe adding an optional `strict` argument to `beginning-of-function`?

**Comment by lionel-** [comment] 2015-10-13 23:21
Should it find the defun that is closest in terms of raw distance, or should it find the next defun at the same level?

```r
# A
function() body

# B is deep inside another call
some_call(other_call(function() {}))

# C has D inside it
function () {
  stuff
  # D
  function() {}
}

#E
function () {}
```
When we are at E, should we find D or C? Similarly, when we are at C, should we find B or A? Note that finding function at the same level is easier.

cc @mmaechler

**Comment by vspinu** [comment] 2015-10-14 08:04
For this we need to see how C++ does it. Maybe we go with the simplest, get next call independently of the level.

**Comment by lionel-** [comment] 2015-10-14 09:12
> Maybe we go with the simplest,

That's not the simplest, we can't just have an inefficient backward search, so we need to go up the next syntactic unit and then parse the tree inside it. There's some overhead involved in calling the syntax travellers but the cost shouldn't grow too much with file size as with backward searches. At least that's my assumption since the beginning so I hope I'm right!

> For this we need to see how C++ does it. 

You're right, in case of doubt, ask the neighbours. Lambdas introduced in c++11 are skipped. In lisp, nested defuns are not recognised either. So we can go for same level.

Though we shouldn't reproduce their behaviour exactly. When called inside D, we first find D, then C. With lisp you would go right to C. I think it's better to have that additional granularity.

**Comment by lionel-** [comment] 2015-10-14 10:06
> we need to go up the next syntactic unit and then parse the tree inside it

Or just climb one unit and search forward for defuns, taking the closest to point. We can do it if that's what we want. In the first case we travel up in one dimension. In the second we travel up in two dimensions. That could even be a setting `ess-flat-travel`.

**Comment by lionel-** [comment] 2015-10-14 10:10
But I'm not sure how flat travel should work with the `-or-paragraph` version... Probably simpler to just go up levels.

**Comment by mmaechler** [comment] 2015-10-14 10:19
Just a short comment:  Note we do have  the bug in #230   that is just when **inside** a function.
I'd recommend fixing that first.
Then moving "from function to function" is at least conceivable... #230 is really a bad bug.   This issue is just about a new feature.

**Comment by lionel-** [comment] 2015-10-14 10:35
I'm fixing everything in one go Martin.

**Comment by vspinu** [comment] 2015-10-14 12:05
Why not use regexp as we are using right now?

**Comment by lionel-** [comment] 2015-10-14 12:09
For efficiency and flexibility. Though as I said above we can climb one syntactic unit up and then search forward for a simple function regex if we are to go with the flat option.

**Comment by vspinu** [comment] 2015-10-14 12:24
One good reason to use syntactic parsing is to generalize the notion of defuns
as we discussed.  Even if we can have an efficient detection of a generic top
level block, that would be worth it.

**Comment by lionel-** [comment] 2015-10-14 12:28
Yes that's what I'm doing. I'm still not convinced we should conflate the notions of defuns and blocks but it'll be easy to propose different versions anyway. We can have a setting `ess-blocks-as-defuns`. Would that work for you?

At the moment I'm thinking of defining a R defun as:
* including the LHS
* including an enclosed function call, no matter what it is. This way we handle `lapply()` `purrr::map()`, all S4 setters, etc.

**Comment by vspinu** [comment] 2015-10-14 15:16
>> On Wed, Oct 14 2015 05:28, Lionel Henry wrote:

> We can have a setting `ess-blocks-as-defuns`. Would that work for you?

Surely it work. defun is just a name. I don't think we are conflating anything,
we are just generalizing the "defun" word, just as other packages, including
emacs-lisp do.

Having said that, we need a way to quickly evaluate an inner nested block if
needed. I don't have any concrete ideas on the UI though.

> At the moment I'm thinking of defining a R defun as:
> * including the LHS
> * including an enclosed function call, no matter what it is. This way we handle `lapply()` `purrr::map()`, all S4 setters, etc.

This makes sense AFAIK.

**Comment by lionel-** [comment] 2015-10-14 20:59
> I don't think we are conflating anything, we are just generalizing the "defun" word,

Well that's what conflating means here.

In the end I think you're right. If we can make travelling and evaluating work for both functions and blocks with one command, we'll have a much simpler UI.

> I don't have any concrete ideas on the UI though.

How about working with innermost defuns as a rule, and with the outermost when called with prefix?

**Comment by vspinu** [comment] 2015-10-14 21:12
> How about working with innermost defuns as a rule, and with the outermost when called with prefix?

I think it should be the other way around. Currently the innermost function is
evaluated, and that's most of the time not the intended behavior (at least in my
case).

May be we can have a toggling command for this. Depending on a boolean setting
the evaluation will behave one way or another. Similarly to what we have with
the ess-eval-visibly.

As to navigation, I though we almost settled on navigating through outer blocks.

**Comment by lionel-** [comment] 2015-10-14 21:20
> and that's most of the time not the intended behavior

It's useful if you are in the midst of developping a function, especially if we generalise evaluation to blocks.

> As to navigation, I though we almost settled on navigating through outer blocks.

Yes, but before reaching the outermost block, we first go through up the hierarchy of blocks, starting from the innermost.

> May be we can have a toggling command for this.

I agree.

**Closed** 2019-01-01 01:18 UTC
Labels: edit:syntax
