### ISSUE TITLE
hang when opening help - on Windows

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#954] opened 2019-07-29 16:55 UTC
Relatively recent change: some commands hang on `?` help-searching.

For instance, either `?data.table::CJ` or 

```r
library(data.table)
?CJ
```

hangs R. It shows the typical status activity, then hangs on `Retrieving RDS aliases...done`. With emacs now unresponsive (`C-g` does nothing), the only recourse I've found is to kill R. (CPU usage is low, so it's not spinning on something.) When that happens, the left (non-R) pane (I usually edit on the left, `*R*` on the right) switches to `*ess-get-words*` and shows just `+ ` (plus and a space).

After the kill, I can look at the available buffers and see `*help[R](data.table::CJ)*`. I can switch to it and it appears to be fully-formed with no artifacts.

If I restart R and attempt something more basic, `?cat`, it comes up just fine. I have not found rhyme-or-reason:

- home-built packages (either installed via `devtools::` or `install.packages`) are **good**
- base packages are **good**
- others are **good**: `zoo`, `dplyr`, `purrr`
- **good**: `?data.table::data.table`
- **bad**: `?data.table::CJ`
- (I have had it hang on other help pages in the last few weeks, but I cannot recall them at the moment; as I find more, I'll add details)

So something specific to this version of `data.table`'s help pages appear to be problematic. I upgraded from 1.12.0 to 1.12.2, restarted R, and ... no change. If it matters, `CJ` is part of the `J` page (not its own `CJ` page). Thinking that the aliasing was a problem, I checked, but `?purrr::walk` works (and is described on `purrr::map`'s page).

At any time, I can just type in `help("CJ", package="data.table")` and get it dumped to the R console (but who wants that :-).

So there are really two points from the issue, only #2 is relevant at the moment to ESS:

1. Something is wrong with that help page. I don't know if it's stuck in the upstream package or somehow my machine is mis-compiling and/or rendering it. I don't know.

2. Where and why is ESS hanging on something that is malformed? Perhaps ESS can be more resilient to the underlying problem and not hang emacs, instead erring and returning to the REPL.

```
GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30
ess-version: 18.10.3snapshot [elpa: 20190728.1931] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20190728.1931/)

R.version
#                _                           
# platform       x86_64-w64-mingw32          
# arch           x86_64                      
# os             mingw32                     
# system         x86_64, mingw32             
# status                                     
# major          3                           
# minor          5.3                         
# year           2019                        
# month          03                          
# day            11                          
# svn rev        76217                       
# language       R                           
# version.string R version 3.5.3 (2019-03-11)
# nickname       Great Truth                 
```

<details><summary>Actual help text for <code>data.table::J</code></summary>

(In case there is something peculiar about *this* page.)

<pre>
\title{ Creates a Join data table }\name{J}\alias{J}\alias{CJ}\alias{SJ}\keyword{ data }\description{
  Creates a \code{data.table} to be passed in as the \code{i} to a \code{[.data.table} join.
}\usage{
# DT[J(\dots)]                           # J() only for use inside DT[\dots].
SJ(\dots)                                # DT[SJ(\dots)]
CJ(\dots, sorted = TRUE, unique = FALSE)  # DT[CJ(\dots)]
}\arguments{
  \item{\dots}{ Each argument is a vector. Generally each vector is the
  same length but if they are not then the usual silent repetition is applied. }
  \item{sorted}{ logical. Should the input be sorted (ascending order)? If \code{FALSE}, the input order is retained. }
  \item{unique}{ logical. When \code{TRUE}, only unique values of each vectors are used (automatically). }
}\details{
    \code{SJ} and \code{CJ} are convenience functions for creating a data.table in the context of a data.table 'query' on \code{x}.

    \code{x[data.table(id)]} is the same as \code{x[J(id)]} but the latter is more readable. Identical alternatives are \code{x[list(id)]} and \code{x[.(id)]}.

    \code{x} must have a key when passing in a join table as the \code{i}. See \code{\link{[.data.table}}
}\value{
  \itemize{
    \code{J} : the same result as calling list. \code{J} is a direct alias for list but results in clearer more readable code.

    \code{SJ} : (S)orted (J)oin. The same value as \code{J()} but additionally \code{setkey()} is called on all the columns in the order they were passed in to \code{SJ}. For efficiency, to invoke a binary merge rather than a repeated binary full search for each row of \code{i}.

    \code{CJ} : (C)ross (J)oin. A \code{data.table} is formed from the cross product of the vectors. For example, 10 ids, and 100 dates, \code{CJ} returns a 1000 row table containing all the dates for all the ids. It gains \code{sorted}, which by default is \code{TRUE} for backwards compatibility. \code{FALSE} retains input order.
  }
}\seealso{ \code{\link{data.table}}, \code{\link{test.data.table}} }\examples{
DT = data.table(A=5:1,B=letters[5:1])
setkey(DT,B)    # re-orders table and marks it sorted.
DT[J("b")]      # returns the 2nd row
DT[.("b")]      # same. Style of package plyr.
DT[list("b")]   # same

# CJ usage examples
CJ(c(5,NA,1), c(1,3,2)) # sorted and keyed data.table
do.call(CJ, list(c(5,NA,1), c(1,3,2))) # same as above
CJ(c(5,NA,1), c(1,3,2), sorted=FALSE) # same order as input, unkeyed
# use for 'unique=' argument
x = c(1,1,2)
y = c(4,6,4)
CJ(x, y) # output columns are automatically named 'x' and 'y'
CJ(x, y, unique=TRUE) # unique(x) and unique(y) are computed automatically

}
</pre>
</details>

**Comment by jabranham** [comment] 2019-07-30 00:06
Thanks for the detailed bug report! Should be fixed now, let me know if you still see this.

**Comment by r2evans** [comment] 2019-07-30 19:12
Looks that that did it, thanks @jabranham!

**Comment by troelsgk** [comment] 2020-01-09 20:27
@r2evans  and @jabranham Thanks for your work! 

I think I just reproduced this error typing ?difftime - and found exactly the situation you described above. Just installed newest ESS version from MELPA - no improvement. 

This is my currently installed version of ESS: (grabbed from MELPA): 20190521.2129 . I never experienced this before upgrading to emacs 28.0.50 (I'm using the builds by http://ppa.launchpad.net/ubuntu-elisp/ppa/ubuntu). 

I am running R version 3.6.2 (2019-12-12). Other help files and the help file of data.table works flawlessly, and difftime also works - outside emacs.

**Comment by hendrikweisser** [comment] 2020-07-08 12:52
I agree with @troelsgk that this issue is not fully fixed. I'm getting the problem with the newest ESS from Melpa (version 20200623.1908), Emacs 26.3 on Windows 10, with R 4.0.1. It hangs reproducibly for me when I type `?p.adjust`. I've set `options(help_type="text")`, in case that matters.
Please have a look at this again, because an error that irretrievably hangs the R session is highly annoying, and so is not being able to use the built-in help to avoid this.

**Comment by mmaechler** [comment] 2020-07-14 07:42
It works fine with the "old" (last release) version 18.02 as downloaded from Vincent Goulet.
(I've never used ESS versions apart from those pre-packaged by Vincent Goulet for the last 15 years or so).
See the ESS web page, tab[Download]  https://ess.r-project.org/index.php?Section=download  and then search down to "Windows"

**Comment by lionel-** [comment] 2020-07-14 09:03
oops, already reopened in #1025, thanks to @hendrikweisser.

**Closed by lionel-** 2020-07-14 09:03 UTC
