### ISSUE TITLE
comment-dwim does not respect ess-indent-with-fancy-comments

### ISSUE THREAD

**Issue by DarwinAwardWinner** [emacs-ess/ESS#434] opened 2017-07-07 23:52 UTC
Open an R-mode file, and put a single-# comment in it starting at column zero. Pressing TAB indents it to column 40 by default. After setting `ess-indent-with-fancy-comments` to nil, TAB now indents the comment to column 0. However, `comment-dwim` still indents that comment to column 40. My expectation is for `comment-dwim` to use the same indentation as TAB.

**Comment by DarwinAwardWinner** [comment] 2017-07-07 23:53
I am using ESS version 16.10-1 installed from MELPA on Emacs 24.5.1.

**Comment by DarwinAwardWinner** [comment] 2018-08-31 05:14
Yes, I still see this. Behavior is unchanged on Emacs 26.1 with ESS current master.

**Comment by jabranham** [comment] 2018-09-30 19:39
Ah, I do in fact see this. I must've misconfigured something the first time.

This is because `comment-dwim` calls `comment-indent`, which indents the line's comment to `comment-column`. 

Since that call to comment-indent is hard coded into comment-dwim, there's not much ESS can do about it. I suppose we could advice comment-dwim, but that seems rather heavy-handed. 

I'm tempted to close this as "not a bug" even though the behavior is a little unexpected. Let's see what others think @vspinu @lionel- ?

**Comment by DarwinAwardWinner** [comment] 2018-10-01 00:38
Then why does it do the expected thing with double-# comments? For example:

```R
## comment-dwim indents this correctly

# comment-dwim indents this wrong
```

**Comment by jabranham** [comment] 2018-10-01 00:55
Ah, good point!

I'll take a look later.

**Comment by vspinu** [comment] 2018-10-05 11:16
I would also say this is not a bug at least on ESS side. 

> Since that call to comment-indent is hard coded into comment-dwim,

I think this is an emacs issue. comment-dwim uses `indent-according-to-mode` in the second part with an explicit comment that `Some modes insist on keeping column 0 comment in column 0`. In any case we should probably set `comment-indent-function` to our indent function.

**Comment by DarwinAwardWinner** [comment] 2018-10-05 16:45
Does that explain why single-# comments are indented differently from others?

**Comment by jabranham** [comment] 2018-10-05 17:11
`(setq-local comment-indent-function #'ess-calculate-indent)` seems to work well but I haven't had time to look into this to make sure it doesn't break other things yet.

**Comment by jabranham** [comment] 2018-12-23 13:58
@DarwinAwardWinner this should be fixed in git master. MELPA usually gets around to rebuilding ESS in four to eight hours. Let me know if it doesn't work for you.

**Comment by DarwinAwardWinner** [comment] 2018-12-24 04:04
I confirm this seems to be fixed. Thanks!

**Closed** 2019-01-01 00:43 UTC
Labels: edit:indent

**Comment by jwhendy** [comment] 2021-12-12 19:31
I don't have any awareness about dwim, and am fairly noob level with ESS; I only know that it's a dependency for Org-mode's src blocks, and don't do anything directly with ESS other than `C-c '` to interactively edit R code in Org-mode. Can someone clarify in simple terms what was fixed from the above? For my case:
- go to new buffer
- `M-x ess-mode`, then `M-x R-mode`
- type in `# test` and hit enter
- gets indented to col 40
- `##` stays as desired

For reference, I'm on:
```
commit b1d299c96e73dc892b0065c1617205dd4b9f8ab8 (HEAD -> master, origin/master, origin/HEAD)
Author: Vitalie Spinu <spinuvit@gmail.com>
Date:   Fri Sep 24 18:06:54 2021 +0200

    Fix matching of partial file names to buffer files in error navigation
    
       (e.g. rlang errors)
```

Do I misunderstand this bug and it's purely about this fancy comments setting? Is what I experience still the default ESS behavior, or is something still awry? If the latter, I can open a new issue, but maybe I just don't understand that ESS can't handle single `#` comments?

**Comment by lionel-** [comment] 2021-12-13 07:05
@jwhendy Use this if you want `#` to be indented at column 0:

```elisp
(setq ess-indent-with-fancy-comments nil)
```

**Comment by jwhendy** [comment] 2021-12-16 04:22
Thanks @lionel- ! I found an SO post about fancy comments and think I better understand what was going on. As usual... I should have spent the 3min of background research *before* coming here, but this issue seemed so close. Thanks for the quick help.
