### ISSUE TITLE
Forming completions hangs emacs -- when the R prompt is `"R> "`

### ISSUE THREAD

**Issue by kwstat** [emacs-ess/ESS#1043] opened 2020-09-02 22:29 UTC
I'm using Emacs 27.1 (or 28) with R 4.0.2 on a Windows 10 machine.  I have  these two possibly relevant configurations:
```
(inferior-ess-r-help-command ".ess.help('%s', help.type='text')\n" )
(ess-use-auto-complete nil)
```
Follow these steps to create the bug:
```
1. Start Emacs
2. M-x R (to start inferior R process)
3. rnorm(9999)
4. ?iris
```

Sometimes, and ONLY SOMETIMES, Emacs will hang with this message "Forming completions for package:devtools".

It's so weird that the crash only happens about 25% of the time, and this makes debugging very, very time consuming and tedious.  Would love to get some suggestions on how to proceed.

Notes:
1. Important to note that the hanging happens only about 20% of the time.  The rest of the time, the help page will correctly display in another buffer.
2. I never had this problem with Emacs 26.  Only with Emacs 27 and 28.
2. I'm not sure if "rnorm(9999)" is necessary, but it seems to increase the chance of failure.
3. A similar issue was reported in the past #44.  I have disabled auto-complete (see the setting above).
4. Hanging happens with "Forming completions", but need not stop at "devtools". The hang can happen with any package in the forming-completions
4. When Emacs hangs, I cannot recover the session in any way (Ctrl-Z, Ctrl-G, Ctrl-C, Ctrl-Break, clicking on the close-window button in the titlebar, etc.)  I have to use Task Manager to kill Emacs.
5. Because of this, I am unable to get a crash dump or other diagnostic (as far as I know).  Please let me know if I'm wrong about this!!!
6. I can run the steps 1-4 several times and it works just fine.
a. If Emacs does NOT hang, I can probably (with 20% probability) repeat the steps without any problem.
b. If Emacs DOES hang, I can kill Emacs, and then (with 20% probability) repeat the steps without any problem.
c. If Emacs DOES hang, and I do NOT kill the hanging Emacs, then opening ANOTHER Emacs session and repeating steps 1-4 WILL hang with 100% probability.  (This will make it much easier to try things for debugging!).
 
7. The "Forming completions" is inside a loop in the function `ess-get-modtime-list` here:
https://github.com/emacs-ess/ESS/blob/cb75588d972b97e597c42108b3c83c2f67947cac/lisp/ess-inf.el
8.  Looking at `ess-get-modtime-list` I see this bit of code
```
                               (prog2
                                       (message "Forming completions for %s..." pack)
                                       (ess-object-names pack index)
                                     (message "Forming completions for %s...done" pack))))))
```
In the `*Messages*` buffer I can see this (when there is no hang):
```
Forming completions for .GlobalEnv...done
Forming completions for ESSR...done
Forming completions for package:stats...done
Forming completions for package:graphics...done
Forming completions for package:grDevices...done
Forming completions for package:utils...done
Forming completions for package:datasets...done
Forming completions for package:httr...done
Forming completions for package:devtools...done
Forming completions for package:usethis...done
Forming completions for .startup...done
Forming completions for package:methods...done
Forming completions for Autoloads...done
Forming completions for package:base...done
Retrieving RDS aliases...done
```
Notice the "done" at the end of each line.  When there IS a hang, the minibuffer shows only
```
Forming completions for package:grDevices"
```
Notice there is no "done" printed when there is a hang. Looking again at `ess-get-modtime-list`, perhaps the problem lies with `ess-object-names`.  When I look at the code for that function, there are 3 FIXMEs.  

In the *ESS* dribble buffer is this (without hang).
```
(R): ess-dialect=R, buf=*Ibuffer*, start-arg=nil
 current-prefix-arg=nil
(inferior-ess: waiting for process to start (before hook)
(inferior-ess 3): waiting for process after hook(R): inferior-ess-language-start=options(STERM='iESS', str.dendrogram.last="'", editor='emacsclient', show.error.locations=TRUE)
(get-object-list R) ..--> (ess-get-modtime-list)
 (ess-search-list ... ) after 'search()
', point-max=306
(nil): created new alist of length 14
 (length alist) : 14
 have re-read pos=1: -> length 0
 (ess-search-list ... ) after 'search()
', point-max=306
Processing RDS files ...
 |--> nil [searching t]
```
If there is a hang, then "point-max=306" is the last thing shown in the dribble buffer.

**Comment by lionel-** [comment] 2020-09-03 06:10
> When Emacs crashes, I cannot recover the session in any way. I have to use Process Explorer to kill Emacs.

Even with repeated `C-g` invokations?

> Because of this, I am unable to get a crash dump

A hang is not a crash, it's usually an infinite loop. Sometimes the infloop happens in such a way that it can't be interrupted, but this is rather rare.

**Comment by kwstat** [comment] 2020-09-03 13:38
Thanks. I tweaked the description.  You correct, Ctrl-g does nothing.  Emacs is 100% frozen. I cannot even click on the "X" in the upper right corner of the titlebar to close the app.  Only via Task Manager (or Process Explorer) can I kill it.

**Comment by jabranham** [comment] 2020-09-04 13:45
Can you make sure you've updated to the latest ESS? There was an issue that I *hope* was fixed in 3c2fb63a2876362699eec922551db9f4685c2fc6 that could've caused this

**Comment by kwstat** [comment] 2020-09-04 14:23
All emacs packages are up to date, including ess 20200903

**Comment by lionel-** [comment] 2020-09-05 08:56
Thank you for all the debugging information you've included in your message @kwstat (don't hesitate posting these in new comments so we get notifications).

Can you please run this to trace all ESS functions in a buffer and then try to reproduce the hang?

```elisp
(dolist (fn (all-completions "ess" obarray))
  (trace-function (intern fn)))
```

**Comment by lionel-** [comment] 2020-09-05 09:02
hmm this one will also trace iESS functions:

```elisp
(let ((fns (union (all-completions "ess" obarray)
                  (all-completions "inferior-ess" obarray))))
  (dolist (fn fns)
    (trace-function (intern fn))))
```

**Comment by kwstat** [comment] 2020-09-08 15:48
Here's the trace at the point of the hang. (Because of the hang, I can only grab this as a screenshot).
![emacs1](https://user-images.githubusercontent.com/484260/92497288-c6d2b780-f1be-11ea-9dd7-12854d4e7bcc.png)

Here's a snippet part of the trace when there is NO hang.  I think this is the relevant portion of the trace, but I'll attach the whole trace below.  I don't know if it is relevant or not, but I think I see this difference in the traces:
Hang: `busy:t busy-end: nil`
No hang: `busy:nil busy-end t`
```

| | | | | | | | | | | | | 14 -> (ess-command "tryCatch(base::print(base::names(package:grDevices), max=1e6), error=function(e){})
" #<buffer  *ess-get-words*> sleep nil nil nil)
| | | | | | | | | | | | | | 15 -> (ess-command--get-proc nil nil)
| | | | | | | | | | | | | | | 16 -> (ess-get-process "R")
| | | | | | | | | | | | | | | 16 <- ess-get-process: #<process R>
| | | | | | | | | | | | | | 15 <- ess-command--get-proc: #<process R>
| | | | | | | | | | | | | | 15 -> (ess-if-verbose-write "(ess-command tryCatch(base::print(base::names(package:grDevices), max=1e6), error=function(e){})
 ..)")
| | | | | | | | | | | | | | 15 <- ess-if-verbose-write: nil
| | | | | | | | | | | | | | 15 -> (inferior-ess-mark-as-busy #<process R>)
| | | | | | | | | | | | | | 15 <- inferior-ess-mark-as-busy: (busy t sec-prompt nil busy-end\? t availability-check nil running-async\? nil funargs-pre-cache (("plot" (("graphics") (("x" . #1="") ("y" . "NULL") ("type" . "p") ("xlim" . "NULL") ("ylim" . "NULL") ("log" . #1#) ("main" . "NULL") ("sub" . "NULL") ("xlab" . "NULL") ("ylab" . "NULL") ("ann" . "par(\"ann\")") ("axes" . "TRUE") ("frame.plot" . "axes") ("panel.first" . "NULL") ("panel.last" . "NULL") ("asp" . "NA") ("..." . #1#)) ("x" "y" "..." "ci" "type" "xlab" "ylab" "ylim" "main" "ci.col" "ci.type" "max.mfrow" "ask" "mar" "oma" "mgp" "xpd" "cex.main" "verbose" "scale" "xlim" "log" "sub" "ann" "axes" "frame.plot" "panel.first" "panel.last" "asp" "center" "edge.root" "nodePar" "edgePar" "leaflab" "dLeaf" "xaxt" "yaxt" "horiz" "zero.line" "verticals" "col.01line" "pch" "legend.text" "formula" "data" "subset" "to" "from" "newpage" "vp" "labels" "hang" "freq" "density" "angle" "col" "border" "lty" "add" "predicted.values" "intervals" "separator" "col.predicted" "col.intervals" "col.separator" "lty.predicted" "lty.intervals" "lty.separator" "plot.type" "main2" "par.fit" "grid" "panel" "cex" "dimen" "abbrev" "which" "caption" "sub.caption" "id.n" "labels.id" "cex.id" "qqline" "cook.levels" "add.smooth" "label.pos" "cex.caption" "rows" "levels" "conf" "absVal" "ci.lty" "xval" "do.points" "col.points" "cex.points" "col.hor" "col.vert" "lwd" "set.pars" "range.bars" "col.range" "xy.labels" "xy.lines" "nc" "yax.flip" "mar.multi" "oma.multi"))) ("print" (("base") (("x" . #1#) ("digits" . "NULL") ("quote" . "TRUE") ("na.print" . "NULL") ("print.gap" . "NULL") ("right" . "FALSE") ("max" . "NULL") ("useSource" . "TRUE") ("..." . #1#)) ("x" "..." "digits" "signif.stars" "intercept" "tol" "se" "sort" "verbose" "indent" "style" ".bibstyle" "prefix" "vsep" "minlevel" "quote" "right" "row.names" "max" "na.print" "print.gap" "useSource" "diag" "upper" "justify" "title" "max.levels" "width" "steps" "showEnv" "newpage" "vp" "cutoff" "max.level" "give.attr" "units" "abbrCollate" "print.x" "deparse" "locale" "symbolic.cor" "loadings" "zero.print" "calendar")))) dbg-buffer #<buffer  *ess.dbg.R*> dbg-active nil tracebug t :accum-buffer #<buffer  *R:accum*> is-recover nil flush-time nil prev-prompt nil average-response-time 0.04534222222222223 last-availability-check (24407 41214 536515 0) last-eval (24407 41209 546689 0) flush-timer nil sp-for-help-changed\? nil)
| | | | | | | | | | | | | | 15 -> (ess-wait-for-process #<process R> nil nil nil)
| | | | | | | | | | | | | | | 16 -> (inferior-ess-ordinary-filter #<process R> "NULL
R> ")
| | | | | | | | | | | | | | | | 17 -> (inferior-ess--set-status #<process R> "NULL
R> ")
| | | | | | | | | | | | | | | | 17 <- inferior-ess--set-status: 6
| | | | | | | | | | | | | | | | 17 -> (ess--if-verbose-write-process-state #<process R> "NULL
R> " "ordinary-filter")
| | | | | | | | | | | | | | | | | 18 -> (ess-if-verbose-write "
ordinary-filter:
    --> busy:nil busy-end:t sec-prompt:nil interruptable:nil <--
    --> running-async:nil callback:nil suppress-next-output:nil <--
    --> dbg-active:nil is-recover:nil <--
    --> string:NULL
R> 
")
| | | | | | | | | | | | | | | | | 18 <- ess-if-verbose-write: nil
| | | | | | | | | | | | | | | | 17 <- ess--if-verbose-write-process-state: nil
```
Here's the whole trace when there is NO hang:
[emacs_trace.txt](https://github.com/emacs-ess/ESS/files/5189311/emacs_trace.txt)

**Comment by lionel-** [comment] 2020-09-08 16:43
These may be long shots but do hangs get resolved when:

* You set `options(max.print = 99999)`?
* You set your prompt to `> `?

**Comment by kwstat** [comment] 2020-09-08 18:29
I switched my prompt from "R> " to "> ".  I've run the test-scenario 20 times and had NO PROBLEMS.  This is very promising.  Very creative thinking @lionel-  !  I'll leave this issue open for a while--while I try using Emacs 28 as my and see what happens.

**Comment by lionel-** [comment] 2020-09-09 07:21
Glad this fixed it! For now it's best not to change your R prompt as it might trip up busy detection. But it is weird that you didn't see any problems on older Emacsen. It's also strange that you couldn't interrupt Emacs.

**Comment by mmaechler** [comment] 2020-09-09 08:08
Changing the prompt, notably to `R> `  which has been a standard in some places, had never been a problem in ESS  before recently.  It's still all tied to the ESS trying to filter all before putting things to the console  --- something that I'd like to be able to turn off .. and still have 99.5% (or more!) of ESS working correctly...

**Comment by lionel-** [comment] 2020-09-09 08:29
We've had busy detection since 2012 https://github.com/emacs-ess/ESS/commit/319a564c2ab9203fb68d2c765d2cfb9ddd22f5ea. What may be changing is the amount of functionality that relies on this but I don't think there has been much change in the last years. We will also need busy detection for the evaluation queue discussed in #1017 so we know when to send the next input.

**Comment by lionel-** [comment] 2020-09-09 08:37
As long as the prompt finishes with `"> "` there should be no issue for detecting it though. I'm not sure what is causing the problems here. Maybe a weird output chunking problem?

**Comment by kwstat** [comment] 2020-09-16 20:55
Thanks to everyone for you help. I no longer experience Emacs hanging while running R.

The fix was to leave the R prompt as "> " instead of my tweak of "R> ".

**Comment by mmaechler** [comment] 2020-09-17 11:06
Actually, I propose we keep this open.   Resetting your prompt to R's default has been good workaround to the problem.
But ESS should really work fine, at least as long as the prompt is regular in *some* sense (which maybe should be defined),
but "R> "  is definitely among the valid ones.

**Comment by jthaman** [comment] 2020-09-18 01:17
Same issue while debugging. R prompt is `Browse[1]> `. Doesn't matter if tracebug is on or off, Emacs session gets crippled.

**Comment by lionel-** [comment] 2020-09-18 05:50
@jthaman Can you provide information about your setup please? OS, Emacs version, ESS version.

**Comment by jthaman** [comment] 2020-09-18 12:21
My mistake, Emacs 27.1, Windows 10, ESS 20200905

**Comment by lionel-** [comment] 2020-09-18 12:28
And you didn't have the issue on older Emacsen?

**Comment by jthaman** [comment] 2020-09-18 12:30
I don't think this occurred in 26.3. I will have to reinstall 26.3 over the weekend and take a look.

 I didn't start using `browser()` a lot until after 27.1 came out, so we have a confounder.

**Comment by kwstat** [comment] 2020-09-18 13:36
Same for my issue (top of this thread).  Emacs 26.3 works okay, but I get random hangs with 27.1 and 28.0.  Both versions used the same (current) ess package.

**Comment by jthaman** [comment] 2020-09-18 14:25
@kwstat When you say 'same issue', you mean that there are no hangs when the prompt is `> `, but you experience hangs when the prompt is `Browse[#]> `. Correct?

**Comment by jthaman** [comment] 2020-09-18 16:17
No issues forming completions while prompt is `Browse[#]> ` on Emacs 26.3, Windows 10, ESS 20200905.

**Comment by r2evans** [comment] 2020-10-01 22:37
My symptom is the same, but perhaps it's a different problem? I've never had a prompt other than `> `, and default is `options(max.print=99999)`, so nothing explicitly set by me. It occurs often when I'm in a function and it appears that ESS is trying to find the formals for that function (uncertain if that's perfectly it or the only one). 

For me, though I'm able to reliably unfreeze emacs by killing the R process.

**Comment by lionel-** [comment] 2020-10-02 07:53
So far the common denominator is windows + emacs 27... This will be hard for us to debug. It's possible it's an Emacs issue on that platform. I still haven't installed emacs 27 on my mac though, I'll try to reproduce when I have some time.

**Comment by r2evans** [comment] 2020-10-03 22:19
Another way that seems to fail repeated (but not perfectly) for me:

1. Edit an R file (I tend to work in functions in R files, but not certain if that's meaningful).
2. Much of the time, I've been in a debugger, so perhaps the prompt is now `Browse[2]> `.
3. Within an *incompletely* function call in the source (perhaps no close-paren, because I'm still typing ... yes I know of packages that can auto-close parens for me).

Sometimes it doesn't hang until I do something else while my cursor is in that incomplete function call: on the R console, let's say I ask for help with `?abline` ... at that point, it hangs.

When I kill `Rterm.exe`, I regain control of emacs, and my source file buffer now switches over to a temporary buffer `*ess-get-words*` with apparently some auto-completion possibles.

I know you're working it, I hope this gives you possible insight into where recent changes in ESS or recent changes in emacs might change expectations. Please let me know if there are profiling/debugging steps that might assist in this situation (though I admit I'm not proficient at debugging emacs itself, just R).

**Comment by jthaman** [comment] 2020-11-10 00:08
> No issues forming completions while prompt is `Browse[#]> ` on Emacs 26.3, Windows 10, ESS 20200905.

I just got bitten by this again, while debugging on Emacs 26.3/Win10.  The Minibuffer is locked and displays `[DB] loading line: <eldoc information from an R package>`. The hang was irrecoverable and I had to use the system monitor to kill the Emacs process.

So I'm not sure that Emacs 26.3 is entirely safe from this bug.

**Comment by lionel-** [comment] 2020-11-28 13:57
If you're having this problem, can you checkout #1065 and see if that helps please?

**Comment by lionel-** [comment] 2020-12-08 11:12
Can one of you try out the latest MELPA version of ESS and see if #1065 helps please?

**Comment by kwstat** [comment] 2020-12-08 15:29
I downloaded ess-20201208.1047 from MELPA and used Emacs 28. I set my prompt to "R>". I performed 10 times the sequence of steps at the very top of this thread (which at that time caused a hang 20% of the time).  I did NOT experience a hang. This is very promising.

**Comment by r2evans** [comment] 2020-12-08 17:49
Ditto, no crash/hang for me given my previous methods (which are slightly different than kwstat's).

Thanks @lionel-, that seems like a good patch!

**Comment by lionel-** [comment] 2020-12-08 17:49
That's great to hear!

**Comment by mmaechler** [comment] 2020-12-09 09:57
Indeed, thanks a lot to @lionel-   also to other  "finally deal with this" issues you've started settling....  This makes me even hope for an official (not-just-MELPA) release of ESS '20.12' ??

**Closed** 2020-12-15 12:34 UTC
Labels: bug:severe, symbols:completion

**Comment by r2evans** [comment] 2020-12-18 22:23
@lionel- I'm not certain this caught all of the corner cases, I just had to kill Rterm again.

Here's the scenario I'm in. I'm not certain how much of this is unnecessary complication:

- I'm in a `.R` file in a package that I `load_all`'d
- I'm debugging a function in that function
- in that function, I'm in another layer of `browser()` within an `lapply`
- I'm using `data.table` (I have no idea if that's relevant), and I'm inside a `[` chain
- on the R console, I type in `?CJ`, and here's the error I see in the last emacs buffer after I kill Rterm:

    ```
    Error: unexpected ')' in ".ess.command(names(formals(DT[CJ)"
        x
    ```

If I can reproduce this, I'll update the reprex.

**Comment by lionel-** [comment] 2020-12-19 10:18
Tracked in #1025

**Comment by lionel-** [comment] 2020-12-21 15:54
@r2evans With the latest dev version of ESS, background commands have a default timeout of 1 second, after which they fail with an informative error. This doesn't fix your problem yet but at least the behaviour is now saner when a background command freezes or hangs.
