### ISSUE TITLE
void-variable: ess-dump-object

### ISSUE THREAD

**Issue by vapniks** [emacs-ess/ESS#322] opened 2016-04-19 13:35 UTC
I get that error when I evaluate `(require 'ess)` after downloading the latest version from melpa.

**Comment by lionel-** [comment] 2016-04-19 13:48
Duplicate of #320, please see there for how to fix this.

**Closed** 2016-04-19 13:48 UTC

**Comment by vapniks** [comment] 2016-04-23 19:18
fixed, thanks.
