### ISSUE TITLE
emacs 28 Eager macro-expansion failure: wrong-number-of-arguments

### ISSUE THREAD

**Issue by parsifal9** [emacs-ess/ESS#1097] opened 2021-01-20 23:03 UTC
Hi ess,

When I start emacs I get the error message
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)
and R/ ess wont work. 
This just started after an upgrade:
ess-version: 18.10.2 [Released git: d4cd65da6dbf] (loaded from /usr/share/emacs/site-lisp/elpa-src/)
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2021-01-20

I see another forum suggesting that the problem is a recent change to "define-obsolete-function-alias" But I dont know if that is helpful or not.

The trace is
```
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 2)
  #f(compiled-function (obsolete-name current-name when &optional docstring) "Set OBSOLETE-NAME's function definition to CURRENT-NAME and mark it obsolete.\n\n(define-obsolete-function-alias \\='old-fun \\='new-fun \"22.1\" \"old-fun's doc.\")\n\nis equivalent to the following two lines of code:\n\n(defalias \\='old-fun \\='new-fun \"old-fun's doc.\")\n(make-obsolete \\='old-fun \\='new-fun \"22.1\")\n\nWHEN should be a string indicating when the function was first\nmade obsolete, for example a date or a release number.\n\nSee the docstrings of `defalias' and `make-obsolete' for more details." #<bytecode -0xd1aaa8a81ac24a8>)('ess-r-devtools-check-package-buildwin 'ess-r-devtools-check-with-winbuilder)
  (define-obsolete-function-alias 'ess-r-devtools-check-package-buildwin 'ess-r-devtools-check-with-winbuilder)
  eval-buffer(#<buffer  *load*-996677> nil "/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." nil t)  ; Reading at buffer position 22503
  load-with-code-conversion("/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." "/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." nil t)
  require(ess-r-package)
  eval-buffer(#<buffer  *load*-560003> nil "/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." nil t)  ; Reading at buffer position 1453
  load-with-code-conversion("/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." "/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." nil t)
  require(ess-r-mode)
  eval-buffer(#<buffer  *load*-939448> nil "/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." nil t)  ; Reading at buffer position 3923
  load-with-code-conversion("/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." "/usr/share/emacs/site-lisp/elpa-src/ess-18.10.2/es..." nil t)
  require(ess-site)
  eval-buffer(#<buffer  *load*> nil "/home/dun280/.emacs" nil t)  ; Reading at buffer position 531
  load-with-code-conversion("/home/dun280/.emacs" "/home/dun280/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x1d2b1d144c43f39e>) #f(compiled-function () #<bytecode 0xc085514c321338c>) t)
  command-line()
  normal-top-level()
```

Bye

**Comment by lionel-** [comment] 2021-01-21 08:51
This is a duplicate of #1085 and is already fixed.

**Closed by lionel-** 2021-01-21 08:51 UTC

**Comment by parsifal9** [comment] 2021-01-22 08:53
It still seems to be there.
```
tamar: git clone https://github.com/emacs-ess/ESS.git
tamar: cd ESS/
tamar: make
tamar: mv ESS ~/local/share/elisp/
tamar: cat ~/.emacs
(add-to-list 'load-path "/home/dun280/local/share/elisp/ESS/lisp")
(require 'ess-site)

tamar: cd ~/local/share/elisp/ESS
tamar: git log | head -2
commit 1c77e93c9f810e95afe75b7f908bbc3aa50e219b
Author: Lionel Henry <lionel.hry@gmail.com>

tamar: emacs
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)
Error loading autoloads: (wrong-number-of-arguments (3 . 4) 2)
```

**Comment by danielreispereira** [comment] 2022-08-19 20:40
Can confirm

> It still seems to be there.
> 
> ```
> tamar: git clone https://github.com/emacs-ess/ESS.git
> tamar: cd ESS/
> tamar: make
> tamar: mv ESS ~/local/share/elisp/
> tamar: cat ~/.emacs
> (add-to-list 'load-path "/home/dun280/local/share/elisp/ESS/lisp")
> (require 'ess-site)
> 
> tamar: cd ~/local/share/elisp/ESS
> tamar: git log | head -2
> commit 1c77e93c9f810e95afe75b7f908bbc3aa50e219b
> Author: Lionel Henry <lionel.hry@gmail.com>
> 
> tamar: emacs
> Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)
> Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)
> Error loading autoloads: (wrong-number-of-arguments (3 . 4) 2)
> ```

Can confirm still there
