### ISSUE TITLE
broken point ("cursor") movement when (eval)ing inside `ess-r-transcript-mode`

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#1013] opened 2020-05-18 15:13 UTC
In previous versions of ESS, navigating *and* evaluation R code was phantastically simple, thanks to our `ess-r-transcript-mode`  which is turned on automagically, e.g., for files ending in `*.Rout` (including those `*.Rout.save` ones, known from base R and package testing).

Let's take one R's own files, download it locally to open in emacs (om a decent OS, in the shell/terminal:)

`     wget https://svn.r-project.org/R/trunk/tests/reg-tests-2.Rout.save
`

If you open in it in an emacs with a correctly working ESS, I use ESS 18.10.2, also starting R, e.g. by
`
emacs -f R  <your_path_to>/reg-tests-2.Rout.save
`
and go to the first prompt, e.g., by `C-s Reg`  you can press `[Enter]` repeatedly to evaluate things to the `*R*` buffer.  At the beginning this also works nicely with current ESS (from github, MELPA, ..).
Things start differing between correctly working and current ESS dramatically, once you get to line 29 (of `reg-tests-2.Rout.save`):  In current ESS, on `[Enter]` there, point (aka "the cursor") just goes one line further (line 30), which is a "+ ...." continuation line of a multi-line evaluation, I'm appending a small screen shot (using `linum-mode` to show line numbers).
![Bildschirmfoto von 2020-05-18 17-09-57](https://user-images.githubusercontent.com/995722/82229521-d9349700-992a-11ea-94d4-8cd07993137c.png)

whereas in ESS 18.10.2 (and *all* earlier versions of ESS), it nicely jumps down to line  69  which is exactly where the next prompt is ... so you can continue the evaluations by continuing with `[Enter]`.

Probably much related to the similarly "new" bugous behavior in issues #956 and #973 .

All of these are probably related to prompt detection, and all of these were working correctly in all released versions of ESS and also for quite some time after releasing ESS 18.10.2 (2018-11-10).

**Comment by lionel-** [comment] 2020-05-18 15:51
May be fixed as part of #1008.

**Comment by jabranham** [comment] 2020-05-19 16:29
@lionel- That wouldn't fix this exact case though, right? Since he's downloading a file from the internet we didn't evaluate it in ESS and it therefore won't have the ANSI escape sequence you use? Or am I misunderstanding something?

@mmaechler If you know it was working in 18.10.2, you could try bisecting to see where the issue occurs.

**Comment by lionel-** [comment] 2020-05-19 16:40
It should be fixed because we'll fall back to rudimentary prompt handling if the prompt isn't tagged.

**Comment by vspinu** [comment] 2020-05-20 21:47
This happens because `(comint-next-prompt 1)`  stops at secondary prompts. Same behavior in the inferior. If you try to navigate to previous prompt in 

```
> for(m in 1:5) {
+   cat("\n",m,":\n")
+   print(as.vector(abbreviate(state.name, minl=m)))
+ }
> 
```

you end up in +. I never noticed this because I don't use `nowait`, but @lionel- , you should have seen it, no?

The issue is that our prompt regexp](https://github.com/emacs-ess/ESS/blob/2e7d36dc9b500ce21c5cb8534ea573669f93ee0b/lisp/ess-custom.el#L1805) tries to capture both long `+ + + +` and proper prompts  like `>`.  

Ideally we would avoid matching single `+ ` there. Any ideas of an improved regexp?

**Comment by lionel-** [comment] 2020-05-21 04:52
> you should have seen it, no?

I have found prompt navigation to be unreliable so I don't use it. Maybe that's because of nowait. Also I use `(setq-local comint-use-prompt-regexp nil)` because this is the only way IESS is usable with evil-mode (the ESS layer in Spacemacs does the same).

For the purpose of prompt navigation, I suggest we only look for `> `, never for `+ `, unless it's trailing (i.e. the REPL is waiting for input).

**Comment by mmaechler** [comment] 2020-05-21 12:21
> May be fixed as part of #1008.

nope.  Stil there  (and yes, I have visibility  `'nowait` )

**Comment by vspinu** [comment] 2020-05-21 17:23
>  I suggest we only look for > , never for + , unless it's trailing

Let's do that, so basically require at least one > in the line.

**Comment by lionel-** [comment] 2020-05-22 09:22
Reopening so we don't forget to add test cases for this.

**Comment by lionel-** [comment] 2020-05-22 09:26
@mmaechler I have rebased https://github.com/lionel-/ESS/tree/fix-prompt on top of master, which includes this fix. Can you please try it and report prompt issues?

(Still not ready to open a PR, but I've been using it for a while and it's been stable for me)

**Comment by mmaechler** [comment] 2020-05-23 13:34
> @mmaechler I have rebased https://github.com/lionel-/ESS/tree/fix-prompt on top of master, which includes this fix. Can you please try it and report prompt issues?

Thank you @lionel- . Yes, this fixes the main problem/bug.  It reverts `*-transcipt-mode`  back to usable,  but should still become better.  I notice that it does not always correctly move forwards, and in some other cases, it gets "off by one line" (similar to the bug #965, but that is indeed still open).  I'll try to construct a small repro case for the first phenonmenon which hopefully should be easy to fix for you.

**Comment by mmaechler** [comment] 2020-05-23 13:44
Oops!  In trying to construct the repr.ex via  
```r
sink("table-ex.Rout"); example(table); sink()
```
I've noticed a  new (?) bug:  ESS makes R using a "crazy" prompt, by adding esc-sequences.
Unfortunately, github is too stupid to allow attaching the `table-ex.Rout` file I get from the above,
but I assume you get the same as I, i.e., things looking as
```
table[39m[23m> require(stats) # for rpois and xtabs

table[39m[23m> ## Simple frequency distribution
table[39m[23m> table(rpois(100, 5))

 0  1  2  3  4  5  6  7  8  9 10 
 1  3 10 17 22 10 10  8 11  4  4 

table[39m[23m> ## Check the design:
```

**Comment by mmaechler** [comment] 2020-05-23 13:54
This is morphing into a different topic ... "No, I don't think it is okay for ESS to change the prompt option; that option really belongs to the useR"

**Comment by lionel-** [comment] 2020-05-23 14:28
Currently, the prompt does not belong to the user. With tagged prompts, the user is in control again. In any case this will be completely optional, but prompt handling should, I think, be simplified when tagged prompt is disabled. This means we won't be able to filter out sequences of `+ + +` when evaluating multi-line inputs.

The idea of using ESC sequences is that they will be filtered out of the output in most situations, since ANSI escapes are becoming standard. The discussion for this feature takes place in #1008.

**Comment by vspinu** [comment] 2020-05-26 08:48
@lionel- adding test for this would just mean to test if the inferior-S-prompt finds what it is supposed to find. Feel free to add, but I think it's an over-engineering.

**Comment by lionel-** [comment] 2020-05-26 09:12
The test should be a motion test in a .Rout buffer. It's about testing UI and preventing regressions like we had in the past.

**Closed** 2020-08-15 08:03 UTC
Labels: bug, process:eval
