### ISSUE TITLE
installation of ess package causes .emacs to fail to load on emacs-version 28.1

### ISSUE THREAD

**Issue by david2038** [emacs-ess/ESS#1218] opened 2022-08-27 05:20 UTC
After adding  the ess package with package-install, the next restart of emacs failed to finish loading .emacs with the error "Wrong number of arguments (3.4),2.

The ess package is 18.10.2. Emacs is 28.1

The problem was in an occurrence of the (define-obsolete-function-alias) function, whose previously optional third argument is now mandatory.

There are 23 occurrences of this function in ess's elisp code. The offending instance is on line 560 of ess-r-package.el.

I changed:
(define-obsolete-function-alias 'ess-r-devtools-check-package-buildwin 'ess-r-devtools-check-with-winbuilder)
to:
(define-obsolete-function-alias 'ess-r-devtools-check-package-buildwin 'ess-r-devtools-check-with-winbuilder "dummy")
and recompiled ess.-r-package.el.

The problem went away, but I don't know the correct value to use for the third argument.

**Comment by lionel-** [comment] 2022-09-04 13:47
Duplicate of #1085, fixed on Jan 6, 2021 by https://github.com/emacs-ess/ESS/commit/9cc5520e1998d03f5dec0fbb1fe71b7cdec38b65

**Closed by lionel-** 2022-09-04 13:47 UTC
Labels: infra:emacs

**Comment by zackw** [comment] 2022-09-23 15:02
Do you intend to make a tagged release of ESS in the near future?  There hasn't been one since 2018 and you're probably going to keep getting duplicates of this bug until you do.
