### ISSUE TITLE
ess fails to start when emacs instance started with git mergetool.

### ISSUE THREAD

**Issue by krivit** [emacs-ess/ESS#562] opened 2018-06-09 07:58 UTC
This is under Debian testing with the following relevant versions:

* GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
* ESS version 17.11

I had submitted it to Debian BTS, and was asked to forward it here.

# To reproduce #

1) Set up a git merge conflict:

```
# Create the repository.
git init test
cd test

# Create and commit a file containing '0' (a syntactically correct R file).
echo '0' > test.R
git add .
git commit -m 'Zero.'

# Create a branch in which '0' is replaced by '1'.
git branch one
git checkout one
echo '1' > test.R
git add .
git commit -m 'One.'

# Replace '0' with '2' in the mater branch.
git checkout master
echo '2' > test.R
git add .
git commit -m 'Two.'

# Attempt a merge, creating a conflict.
git checkout one
git merge master
```

2) Try running mergetool with emacs as editor:

```
git mergetool -t emerge
```

# Expected result: #

A three-way merge interface comes up with files open in ESS R mode.

# Actual result: #

Empty emacs buffer appears, with the following message in the minibuffer:
```
ess-mode: Customise alist is not specified, nor  ess-local-customize-alist is set.
```

**Comment by eddelbuettel** [comment] 2018-06-09 14:54
Thanks for bringing it here.  For the record the initial bug report was [here](https://bugs.debian.org/901122).

**Comment by jabranham** [comment] 2018-06-09 15:09
How did you install ESS, and can you post the value of `auto-mode-alist`? 

It would be helpful to see a backtrace too. Can you put `(setq debug-on-error t)` in your Emacs config file, produce this bug, and post what appears in the `*Backtrace*` buffer?

**Comment by lionel-** [comment] 2018-06-09 15:14
I think the cause of this kind of failure is that `major-mode` for all ESS modes is `ess-mode` and running `(ess-mode)` doesn't work.

**Comment by jabranham** [comment] 2018-06-09 15:17
Right, I'm trying to understand how `(ess-mode)` gets called. Shouldn't `.R` files call `R-mode` from `auto-mode-alist`?

**Comment by krivit** [comment] 2018-06-10 02:48
@jabranham, I installed ESS by installing the Debian package `ess`. Here's the rest of it:

## `auto-mode-alist` value ##
```
(("\\.sp\\'" . S-mode)
 ("/R/.*\\.q\\'" . R-mode)
 ("\\.[qsS]\\'" . S-mode)
 ("\\.ssc\\'" . S-mode)
 ("\\.SSC\\'" . S-mode)
 ("\\.[rR]\\'" . R-mode)
 ("\\.[rR]nw\\'" . Rnw-mode)
 ("\\.[sS]nw\\'" . Snw-mode)
 ("\\.[rR]profile\\'" . R-mode)
 ("NAMESPACE\\'" . R-mode)
 ("CITATION\\'" . R-mode)
 ("\\.omg\\'" . omegahat-mode)
 ("\\.hat\\'" . omegahat-mode)
 ("\\.lsp\\'" . XLS-mode)
 ("\\.do\\'" . STA-mode)
 ("\\.ado\\'" . STA-mode)
 ("\\.[Ss][Aa][Ss]\\'" . SAS-mode)
 ("\\.[Ss]t\\'" . S-transcript-mode)
 ("\\.Sout" . S-transcript-mode)
 ("\\.[Rr]out" . R-transcript-mode)
 ("\\.Rd\\'" . Rd-mode)
 ("\\.[Bb][Uu][Gg]\\'" . ess-bugs-mode)
 ("\\.[Bb][Oo][Gg]\\'" . ess-bugs-mode)
 ("\\.[Bb][Mm][Dd]\\'" . ess-bugs-mode)
 ("\\.[Jj][Aa][Gg]\\'" . ess-jags-mode)
 ("\\.[Jj][Oo][Gg]\\'" . ess-jags-mode)
 ("\\.[Jj][Mm][Dd]\\'" . ess-jags-mode)
 ("\\.jl\\'" . ess-julia-mode)
 ("\\.jl\\'" . julia-mode)
 ("\\.upstart\\'" . upstart-mode)
 ("TODO\\'" . todoo-mode)
 ("\\.sl\\'" . slang-mode)
 ("/rfc[0-9]+\\.txt\\(\\.gz\\)?\\'" . rfcview-mode)
 ("\\.pod\\'" . pod-mode)
 ("muttrc\\'" . muttrc-mode)
 ("\\.mpl\\'" . maplev-mode)
 ("\\.[Cc][Ss][Vv]\\'" . csv-mode)
 ("apache2\\.conf\\'" . apache-mode)
 ("\\.tlc\\'" . tlc-mode)
 ("\\.plt\\'" . quack-pltfile-mode)
 ("\\.m$" . matlab-mode)
 ("\\.dot\\'" . graphviz-dot-mode)
 ("sites-\\(available\\|enabled\\)/" . apache-mode)
 ("access\\.conf\\'" . apache-mode)
 ("srm\\.conf\\'" . apache-mode)
 ("httpd\\.conf\\'" . apache-mode)
 ("\\.htaccess\\'" . apache-mode)
 ("CMakeLists\\.txt\\'" . cmake-mode)
 ("\\.cmake\\'" . cmake-mode)
 ("\\.at\\'" . autotest-mode)
 ("\\.hva\\'" . latex-mode)
 ("\\.drv\\'" . latex-mode)
 ("\\.asy$" . asy-mode)
 ("\\.gpg\\(~\\|\\.~[0-9]+~\\)?\\'" nil epa-file)
 ("\\.\\(?:3fr\\|a\\(?:r[tw]\\|vs\\)\\|bmp[23]?\\|c\\(?:als?\\|myka?\\|r[2w]\\|u[rt]\\)\\|d\\(?:c[mrx]\\|ds\\|jvu\\|ng\\|px\\)\\|exr\\|f\\(?:ax\\|its\\)\\|gif\\(?:87\\)?\\|hrz\\|ic\\(?:on\\|[bo]\\)\\|j\\(?:2c\\|ng\\|p\\(?:eg\\|[2cg]\\)\\)\\|k\\(?:25\\|dc\\)\\|m\\(?:iff\\|ng\\|rw\\|s\\(?:l\\|vg\\)\\|tv\\)\\|nef\\|o\\(?:rf\\|tb\\)\\|p\\(?:bm\\|c\\(?:ds\\|[dltx]\\)\\|db\\|ef\\|gm\\|i\\(?:ct\\|x\\)\\|jpeg\\|n\\(?:g\\(?:24\\|32\\|8\\)\\|[gm]\\)\\|pm\\|sd\\|tif\\|wp\\)\\|r\\(?:a[fs]\\|gb[ao]?\\|l[ae]\\)\\|s\\(?:c[rt]\\|fw\\|gi\\|r[2f]\\|un\\|vgz?\\)\\|t\\(?:ga\\|i\\(?:ff\\(?:64\\)?\\|le\\|m\\)\\|tf\\)\\|uyvy\\|v\\(?:da\\|i\\(?:car\\|d\\|ff\\)\\|st\\)\\|w\\(?:bmp\\|pg\\)\\|x\\(?:3f\\|bm\\|cf\\|pm\\|wd\\|[cv]\\)\\|y\\(?:cbcra?\\|uv\\)\\)\\'" . image-mode)
 ("\\.elc\\'" . elisp-byte-code-mode)
 ("\\.dz\\'" nil jka-compr)
 ("\\.xz\\'" nil jka-compr)
 ("\\.lzma\\'" nil jka-compr)
 ("\\.lz\\'" nil jka-compr)
 ("\\.g?z\\'" nil jka-compr)
 ("\\.bz2\\'" nil jka-compr)
 ("\\.Z\\'" nil jka-compr)
 ("\\.vr[hi]?\\'" . vera-mode)
 ("\\(?:\\.\\(?:rbw?\\|ru\\|rake\\|thor\\|jbuilder\\|rabl\\|gemspec\\|podspec\\)\\|/\\(?:Gem\\|Rake\\|Cap\\|Thor\\|Puppet\\|Berks\\|Vagrant\\|Guard\\|Pod\\)file\\)\\'" . ruby-mode)
 ("\\.re?st\\'" . rst-mode)
 ("\\.pyw?\\'" . python-mode)
 ("\\.scss\\'" . scss-mode)
 ("\\.awk\\'" . awk-mode)
 ("\\.\\(u?lpc\\|pike\\|pmod\\(\\.in\\)?\\)\\'" . pike-mode)
 ("\\.idl\\'" . idl-mode)
 ("\\.java\\'" . java-mode)
 ("\\.m\\'" . objc-mode)
 ("\\.ii\\'" . c++-mode)
 ("\\.i\\'" . c-mode)
 ("\\.lex\\'" . c-mode)
 ("\\.y\\(acc\\)?\\'" . c-mode)
 ("\\.[ch]\\'" . c-mode)
 ("\\.\\(CC?\\|HH?\\)\\'" . c++-mode)
 ("\\.[ch]\\(pp\\|xx\\|\\+\\+\\)\\'" . c++-mode)
 ("\\.\\(cc\\|hh\\)\\'" . c++-mode)
 ("\\.\\(bat\\|cmd\\)\\'" . bat-mode)
 ("\\.[sx]?html?\\(\\.[a-zA-Z_]+\\)?\\'" . html-mode)
 ("\\.svgz?\\'" . image-mode)
 ("\\.svgz?\\'" . xml-mode)
 ("\\.x[bp]m\\'" . image-mode)
 ("\\.x[bp]m\\'" . c-mode)
 ("\\.p[bpgn]m\\'" . image-mode)
 ("\\.tiff?\\'" . image-mode)
 ("\\.gif\\'" . image-mode)
 ("\\.png\\'" . image-mode)
 ("\\.jpe?g\\'" . image-mode)
 ("\\.te?xt\\'" . text-mode)
 ("\\.[tT]e[xX]\\'" . tex-mode)
 ("\\.ins\\'" . tex-mode)
 ("\\.ltx\\'" . latex-mode)
 ("\\.dtx\\'" . doctex-mode)
 ("\\.org\\'" . org-mode)
 ("\\.el\\'" . emacs-lisp-mode)
 ("Project\\.ede\\'" . emacs-lisp-mode)
 ("\\.\\(scm\\|stk\\|ss\\|sch\\)\\'" . scheme-mode)
 ("\\.l\\'" . lisp-mode)
 ("\\.li?sp\\'" . lisp-mode)
 ("\\.[fF]\\'" . fortran-mode)
 ("\\.for\\'" . fortran-mode)
 ("\\.p\\'" . pascal-mode)
 ("\\.pas\\'" . pascal-mode)
 ("\\.\\(dpr\\|DPR\\)\\'" . delphi-mode)
 ("\\.ad[abs]\\'" . ada-mode)
 ("\\.ad[bs].dg\\'" . ada-mode)
 ("\\.\\([pP]\\([Llm]\\|erl\\|od\\)\\|al\\)\\'" . perl-mode)
 ("Imakefile\\'" . makefile-imake-mode)
 ("Makeppfile\\(?:\\.mk\\)?\\'" . makefile-makepp-mode)
 ("\\.makepp\\'" . makefile-makepp-mode)
 ("\\.mk\\'" . makefile-gmake-mode)
 ("\\.make\\'" . makefile-gmake-mode)
 ("[Mm]akefile\\'" . makefile-gmake-mode)
 ("\\.am\\'" . makefile-automake-mode)
 ("\\.texinfo\\'" . texinfo-mode)
 ("\\.te?xi\\'" . texinfo-mode)
 ("\\.[sS]\\'" . asm-mode)
 ("\\.asm\\'" . asm-mode)
 ("\\.css\\'" . css-mode)
 ("\\.mixal\\'" . mixal-mode)
 ("\\.gcov\\'" . compilation-mode)
 ("/\\.[a-z0-9-]*gdbinit" . gdb-script-mode)
 ("-gdb\\.gdb" . gdb-script-mode)
 ("[cC]hange\\.?[lL]og?\\'" . change-log-mode)
 ("[cC]hange[lL]og[-.][0-9]+\\'" . change-log-mode)
 ("\\$CHANGE_LOG\\$\\.TXT" . change-log-mode)
 ("\\.scm\\.[0-9]*\\'" . scheme-mode)
 ("\\.[ckz]?sh\\'\\|\\.shar\\'\\|/\\.z?profile\\'" . sh-mode)
 ("\\.bash\\'" . sh-mode)
 ("\\(/\\|\\`\\)\\.\\(bash_\\(profile\\|history\\|log\\(in\\|out\\)\\)\\|z?log\\(in\\|out\\)\\)\\'" . sh-mode)
 ("\\(/\\|\\`\\)\\.\\(shrc\\|[kz]shrc\\|bashrc\\|t?cshrc\\|esrc\\)\\'" . sh-mode)
 ("\\(/\\|\\`\\)\\.\\([kz]shenv\\|xinitrc\\|startxrc\\|xsession\\)\\'" . sh-mode)
 ("\\.m?spec\\'" . sh-mode)
 ("\\.m[mes]\\'" . nroff-mode)
 ("\\.man\\'" . nroff-mode)
 ("\\.sty\\'" . latex-mode)
 ("\\.cl[so]\\'" . latex-mode)
 ("\\.bbl\\'" . latex-mode)
 ("\\.bib\\'" . bibtex-mode)
 ("\\.bst\\'" . bibtex-style-mode)
 ("\\.sql\\'" . sql-mode)
 ("\\.m[4c]\\'" . m4-mode)
 ("\\.mf\\'" . metafont-mode)
 ("\\.mp\\'" . metapost-mode)
 ("\\.vhdl?\\'" . vhdl-mode)
 ("\\.article\\'" . text-mode)
 ("\\.letter\\'" . text-mode)
 ("\\.i?tcl\\'" . tcl-mode)
 ("\\.exp\\'" . tcl-mode)
 ("\\.itk\\'" . tcl-mode)
 ("\\.icn\\'" . icon-mode)
 ("\\.sim\\'" . simula-mode)
 ("\\.mss\\'" . scribe-mode)
 ("\\.f9[05]\\'" . f90-mode)
 ("\\.f0[38]\\'" . f90-mode)
 ("\\.indent\\.pro\\'" . fundamental-mode)
 ("\\.\\(pro\\|PRO\\)\\'" . idlwave-mode)
 ("\\.srt\\'" . srecode-template-mode)
 ("\\.prolog\\'" . prolog-mode)
 ("\\.tar\\'" . tar-mode)
 ("\\.\\(arc\\|zip\\|lzh\\|lha\\|zoo\\|[jew]ar\\|xpi\\|rar\\|7z\\|ARC\\|ZIP\\|LZH\\|LHA\\|ZOO\\|[JEW]AR\\|XPI\\|RAR\\|7Z\\)\\'" . archive-mode)
 ("\\.oxt\\'" . archive-mode)
 ("\\.\\(deb\\|[oi]pk\\)\\'" . archive-mode)
 ("\\`/tmp/Re" . text-mode)
 ("/Message[0-9]*\\'" . text-mode)
 ("\\`/tmp/fol/" . text-mode)
 ("\\.oak\\'" . scheme-mode)
 ("\\.sgml?\\'" . sgml-mode)
 ("\\.x[ms]l\\'" . xml-mode)
 ("\\.dbk\\'" . xml-mode)
 ("\\.dtd\\'" . sgml-mode)
 ("\\.ds\\(ss\\)?l\\'" . dsssl-mode)
 ("\\.jsm?\\'" . javascript-mode)
 ("\\.json\\'" . javascript-mode)
 ("\\.[ds]?vh?\\'" . verilog-mode)
 ("\\.by\\'" . bovine-grammar-mode)
 ("\\.wy\\'" . wisent-grammar-mode)
 ("[:/\\]\\..*\\(emacs\\|gnus\\|viper\\)\\'" . emacs-lisp-mode)
 ("\\`\\..*emacs\\'" . emacs-lisp-mode)
 ("[:/]_emacs\\'" . emacs-lisp-mode)
 ("/crontab\\.X*[0-9]+\\'" . shell-script-mode)
 ("\\.ml\\'" . lisp-mode)
 ("\\.ld[si]?\\'" . ld-script-mode)
 ("ld\\.?script\\'" . ld-script-mode)
 ("\\.xs\\'" . c-mode)
 ("\\.x[abdsru]?[cnw]?\\'" . ld-script-mode)
 ("\\.zone\\'" . dns-mode)
 ("\\.soa\\'" . dns-mode)
 ("\\.asd\\'" . lisp-mode)
 ("\\.\\(asn\\|mib\\|smi\\)\\'" . snmp-mode)
 ("\\.\\(as\\|mi\\|sm\\)2\\'" . snmpv2-mode)
 ("\\.\\(diffs?\\|patch\\|rej\\)\\'" . diff-mode)
 ("\\.\\(dif\\|pat\\)\\'" . diff-mode)
 ("\\.[eE]?[pP][sS]\\'" . ps-mode)
 ("\\.\\(?:PDF\\|DVI\\|OD[FGPST]\\|DOCX?\\|XLSX?\\|PPTX?\\|pdf\\|djvu\\|dvi\\|od[fgpst]\\|docx?\\|xlsx?\\|pptx?\\)\\'" . doc-view-mode-maybe)
 ("configure\\.\\(ac\\|in\\)\\'" . autoconf-mode)
 ("\\.s\\(v\\|iv\\|ieve\\)\\'" . sieve-mode)
 ("BROWSE\\'" . ebrowse-tree-mode)
 ("\\.ebrowse\\'" . ebrowse-tree-mode)
 ("#\\*mail\\*" . mail-mode)
 ("\\.g\\'" . antlr-mode)
 ("\\.mod\\'" . m2-mode)
 ("\\.ses\\'" . ses-mode)
 ("\\.docbook\\'" . sgml-mode)
 ("\\.com\\'" . dcl-mode)
 ("/config\\.\\(?:bat\\|log\\)\\'" . fundamental-mode)
 ("\\.\\(?:[iI][nN][iI]\\|[lL][sS][tT]\\|[rR][eE][gG]\\|[sS][yY][sS]\\)\\'" . conf-mode)
 ("\\.\\(?:desktop\\|la\\)\\'" . conf-unix-mode)
 ("\\.ppd\\'" . conf-ppd-mode)
 ("java.+\\.conf\\'" . conf-javaprop-mode)
 ("\\.properties\\(?:\\.[a-zA-Z0-9._-]+\\)?\\'" . conf-javaprop-mode)
 ("\\`/etc/\\(?:DIR_COLORS\\|ethers\\|.?fstab\\|.*hosts\\|lesskey\\|login\\.?de\\(?:fs\\|vperm\\)\\|magic\\|mtab\\|pam\\.d/.*\\|permissions\\(?:\\.d/.+\\)?\\|protocols\\|rpc\\|services\\)\\'" . conf-space-mode)
 ("\\`/etc/\\(?:acpid?/.+\\|aliases\\(?:\\.d/.+\\)?\\|default/.+\\|group-?\\|hosts\\..+\\|inittab\\|ksysguarddrc\\|opera6rc\\|passwd-?\\|shadow-?\\|sysconfig/.+\\)\\'" . conf-mode)
 ("[cC]hange[lL]og[-.][-0-9a-z]+\\'" . change-log-mode)
 ("/\\.?\\(?:gitconfig\\|gnokiirc\\|hgrc\\|kde.*rc\\|mime\\.types\\|wgetrc\\)\\'" . conf-mode)
 ("/\\.\\(?:enigma\\|gltron\\|gtk\\|hxplayer\\|net\\|neverball\\|qt/.+\\|realplayer\\|scummvm\\|sversion\\|sylpheed/.+\\|xmp\\)rc\\'" . conf-mode)
 ("/\\.\\(?:gdbtkinit\\|grip\\|orbital/.+txt\\|rhosts\\|tuxracer/options\\)\\'" . conf-mode)
 ("/\\.?X\\(?:default\\|resource\\|re\\)s\\>" . conf-xdefaults-mode)
 ("/X11.+app-defaults/\\|\\.ad\\'" . conf-xdefaults-mode)
 ("/X11.+locale/.+/Compose\\'" . conf-colon-mode)
 ("/X11.+locale/compose\\.dir\\'" . conf-javaprop-mode)
 ("\\.~?[0-9]+\\.[0-9][-.0-9]*~?\\'" nil t)
 ("\\.\\(?:orig\\|in\\|[bB][aA][kK]\\)\\'" nil t)
 ("[/.]c\\(?:on\\)?f\\(?:i?g\\)?\\(?:\\.[a-zA-Z0-9._-]+\\)?\\'" . conf-mode-maybe)
 ("\\.[1-9]\\'" . nroff-mode)
 ("\\.tgz\\'" . tar-mode)
 ("\\.tbz2?\\'" . tar-mode)
 ("\\.txz\\'" . tar-mode)
 ("\\.markdown\\'" . markdown-mode)
 ("\\.md\\'" . markdown-mode))
```

## Backtrace ##
```
Debugger entered--Lisp error: (error "Customise alist is not specified, nor  ess-local-customize-alist is set.")
  signal(error ("Customise alist is not specified, nor  ess-local-customize-alist is set."))
  error("Customise alist is not specified, nor  ess-local-customize-alist is set.")
  ess-mode()
  emerge-copy-modes(#<buffer test_LOCAL_521.R>)
  emerge-setup-with-ancestor(#<buffer test_LOCAL_521.R> "./test_LOCAL_521.R" #<buffer test_REMOTE_521.R> "./test_REMOTE_521.R" #<buffer test_BASE_521.R> "./test_BASE_521.R" nil ((lambda nil (emerge-command-exit "test.R"))) nil)
  emerge-files-with-ancestor-internal("./test_LOCAL_521.R" "./test_REMOTE_521.R" "./test_BASE_521.R" nil ((lambda nil (emerge-command-exit "test.R"))))
  emerge-files-with-ancestor-command()
  command-line-1(("-f" "emerge-files-with-ancestor-command" "./test_LOCAL_521.R" "./test_REMOTE_521.R" "./test_BASE_521.R" "test.R"))
  command-line()
  normal-top-level()
```

**Comment by jabranham** [comment] 2018-06-10 14:17
Oh, so it's trying to copy the major mode by looking at `major-mode` and just calling that function. That's sensible, I guess. 

Perhaps we ought to change ess so it follows the more standard way of setting major mode names?

**Comment by lionel-** [comment] 2018-06-10 14:29
At some point we should create all the major-modes by proper derivation.

**Comment by vspinu** [comment] 2018-06-11 12:00
The notorious issue, again :/ 

I propose that we tackle this imediately after the release. Let's ESS 18.09(?) be the last one with the bulky ess-mode and support for emacs 24.

**Comment by jabranham** [comment] 2018-11-09 13:45
I'm closing this. It's fixed in `next` and will be in the next non-patch release (e.g. not 18.10.<num> but the release after that, possibly 19.04)

**Closed by jabranham** 2018-11-09 13:45 UTC
Labels: infra
