### ISSUE TITLE
ESS and piping

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#311] opened 2016-04-05 01:34 UTC
Hi - 

Is there any way that ESS supports autocompletion of piped objects (via magrittr/dplyr) in R? 

For example:

```R
library(nycflights13)

flights %>% 
    select(dep_ ||
```

where `||` represents point should complete "dep_delay"

**Comment by lionel-** [comment] 2016-04-05 01:44
Not currently. Duplicate of #253

**Closed by lionel-** 2016-04-05 01:44 UTC

**Comment by LaDilettante** [comment] 2017-04-20 18:49
#253 was last discussed in 2015. Given how the tidyverse has become very popular, would you consider this work high priority?
