### ISSUE TITLE
Taking history snapshots

### ISSUE THREAD

**Issue by AntonioFasano** [emacs-ess/ESS#983] opened 2020-02-01 17:01 UTC
I would like to make an R function to save the session transcript until the function is called in an RDS file. 
Assuming there is no history file in the working directory, standard R would be:

    hist_till_now <- function(){
      savehistory()
      rds <- paste0(strftime(Sys.time(), "%Y%m%d-%H%M"), ".rds")
      saveRDS(readLines(".Rhistory"), rds)
      file.remove(".Rhistory") 
    }

There are better ways to do this, by the way the main idea is taking multiple snapshots of your work progressing.  

The problem with ESS is that `savehistory()` seems not implemented. Are there some alternative ways to save the transcript  within an R function?

Note that I have read marginally similar threads here, such as [issue-530971662](https://github.com/emacs-ess/ESS/issues/970#issue-530971662), but they focus on saving the history on exit, while I would like the save to happen in an R function before exiting the session.

**Comment by jabranham** [comment] 2020-02-17 15:17
Closing as a duplicate of #291.

**Closed by jabranham** 2020-02-17 15:17 UTC
