### ISSUE TITLE
Problems with traceback when sourcing files

### ISSUE THREAD

**Issue by ganesh-krishnan** [emacs-ess/ESS#430] opened 2017-06-15 20:30 UTC
When I source file using C-c C-l (which calls `.ess.source()`), the traceback output stops at the `.ess.source()` level.

**Reproducible example**
Create a file test.R with:

```
abc <- 1
def
```

Now source with C-c C-l. Traceback output is shown below:

```
6: stop(msg, call. = FALSE)
5: value[[3L]](cond)
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
3: tryCatchList(expr, classes, parentenv, handlers)
2: tryCatch(ss(file, echo = visibly, local = local, print.eval = output, 
       max.deparse.length = max.deparse.length, keep.source = keep.source), 
       error = function(x) {
           if (fake.source) {
               .ess.file.remove(file)
           }
           msg <- .ess.strip.error(x$message, file)
           stop(msg, call. = FALSE)
       })
1: .ess.source("test.R", visibly = FALSE, output = TRUE)
```

I'm on R version 3.3.2 with ESS version 16.10-1. 

Is there something I'm missing or is this a bug?

**Comment by mmaechler** [comment] 2017-06-16 07:07
Yes, this is a bug..... and indeed a regression.   The fact that R's
traceback() stops with .ess_source(...)  is unfortunate... but maybe not
easy to workaround because we (ESS) uses  tryCatch() inside .ess_source()
so "we" catch the error... maybe we "treat it" differently (i.e. _should_ be smartert in treating it)

OTOH, note that if you use a bit a larger file,
then  ESS   C-c `  (or via menu: [ESS] -> [Tracebug] -> [Show traceback])
gives a nice  *ess-traceback* buffer:

    -----------------------------------------------------------------------------
    + Error in eval(ei, envir) (from source-err.R#5) : object 'def' not found


    5: eval(ei, envir)
    4: eval(ei, envir)
    3: withVisible(eval(ei, envir))
    2: ss(file, echo = visibly, local = local, print.eval = output, 
	   max.deparse.length = max.deparse.length, keep.source = TRUE)
    1: .ess.source("/u/maechler/emacs/ess/etc/source-err.R", visibly = FALSE, 
	   output = TRUE)
    -----------------------------------------------------------------------------


in which the first line contains  file + line-number
which is even clickable, so you jump to the place of where the error
happened which is nice.

**Comment by ess-core** [comment] 2017-06-16 10:53
I don't know other fix for this than to remove that tryCatch. This issue is
rather annoying especially in the context of package development.

That tryCatch is there to clean up the temporary source files, but that could be
achieved with on.exit as well.


 Vitalie

>> On Thu, Jun 15 2017 13:30, Ganesh Krishnan wrote:

> When I source file using C-c C-l (which calls `.ess.source()`), the traceback output stops at the `.ess.source()` level.

> **Reproducible example**
> Create a file test.R with:

> ```
> abc <- 1
> def
> ```

> Now source with C-c C-l. Traceback output is shown below:

> ```
> 6: stop(msg, call. = FALSE)
> 5: value[[3L]](cond)
> 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 3: tryCatchList(expr, classes, parentenv, handlers)
> 2: tryCatch(ss(file, echo = visibly, local = local, print.eval = output, 
>        max.deparse.length = max.deparse.length, keep.source = keep.source), 
>        error = function(x) {
>            if (fake.source) {
>                .ess.file.remove(file)
>            }
>            msg <- .ess.strip.error(x$message, file)
>            stop(msg, call. = FALSE)
>        })
> 1: .ess.source("test.R", visibly = FALSE, output = TRUE)
> ```

> I'm on R version 3.3.2 with ESS version 16.10-1. 

> Is there something I'm missing or is this a bug?

**Comment by ganesh-krishnan** [comment] 2017-06-18 06:49
@mmaechler ESS traceback accessed via C-` is pretty good. So that solves my problem. Thanks!

**Comment by ganesh-krishnan** [comment] 2017-06-21 21:29
So follow up on this. I don't see the line numbers for the error in ESS traceback a lot of the time. Is there any condition as to when I would see the line number and when not?

**Comment by ganesh-krishnan** [comment] 2017-06-21 22:17
Ok I went ahead and implement Vitalie's idea of using `on.exit`. This is how `.ess.source` will now look:

```
.ess.source <- function (file, visibly = TRUE, output = FALSE, max.deparse.length = 300, 
    local = NULL, fake.source = FALSE, keep.source = TRUE, message.prefix = "") 
{
    if (is.null(local)) {
        local <- if (.ess.Rversion > "2.13") 
            parent.frame()
        else FALSE
    }
    ss <- if (.ess.Rversion >= "2.8") 
        base::source
          else function(..., keep.source) base::source(...)
    
    on.exit({
        if (fake.source)
            .ess.file.remove(file)
    })
    
    out <- ss(file, echo = visibly, local = local, print.eval = output, 
              max.deparse.length = max.deparse.length, keep.source = keep.source)
    
    cat(sprintf("%sSourced file %s\n", message.prefix, file))
    invisible(out$value)
}
```
The previous definition also had `.ess.strip.error`. I wasn't sure what it was for. If you let me know, I can add that in as well and create a PR

**Comment by richardsc** [comment] 2017-10-10 12:15
Just bumping this issue to see if @ganesh-krishnan fix does the trick, and can be implemented, or if we're waiting for something else. I hit this bug quite a bit (I know, I know, if I programmed fewer errors I wouldn't have to deal with it ... :smile), and would love to see it work the way it used to.

**Comment by ganesh-krishnan** [comment] 2017-10-12 17:05
@richardsc The function above works pretty well. I have put into my `.Rprofile` until this issue is sorted in ESS.

**Comment by ganesh-krishnan** [comment] 2017-10-12 17:18
Ok, I have the local branch with the change. But I'm unable to push the branch upstream. It says I don't have permission. How do I open a PR for this change?

**Comment by richardsc** [comment] 2017-10-12 17:50
Ah, I see -- your new `.ess.source()` can just be implemented locally. I'll try that!

Since you're not a collaborator on this repo, you'll have to make your own fork (i.e. make a copy of the repo in your own Github account), make the changes on that version, and then create a PR from your fork. See e.g.

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by ganesh-krishnan** [comment] 2017-10-15 01:44
Thanks! Had a brain freeze :) I'll fork the repo and open a PR.

**Comment by ganesh-krishnan** [comment] 2017-10-15 02:02
Ok created the PR [here](https://github.com/emacs-ess/ESS/pull/459).

**Comment by vspinu** [comment] 2017-10-15 08:52
Merged. Thanks @ganesh-krishnan!

**Closed by vspinu** 2017-10-15 08:52 UTC
Labels: bug
