### ISSUE TITLE
Subtle indentation problem

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#254] opened 2015-10-08 08:42 UTC
Indentation:  There may be **two** problems here :
1) The (RRR default) indentation of the opening `{`  which I'd prefer at 0
2) the '# ^-' marked wrong indentation of `otherwise...`

Note (to myself:  use "code fences", i.e. \`\`\`r  ... \`\`\` -- 4 char. indenting is not good enough)
```r
splineDesign <-
    function(knots, x, ord = 4, derivs = integer(nx), outer.ok = FALSE,
             sparse = FALSE)
### Yes, I do *NOT* want to indent the '{' in this case :
{
    if((nk <- length(knots <- as.numeric(knots))) <= 0)
        stop("bla")
        otherwise.continue()
### ^--- is indented "as if" the '{' above was indented
}
```

**Comment by lionel-** [comment] 2015-10-08 08:52
For (1) we'd need a new setting as I suggested in #227. It was decided that we didn't need one here.

(2) is a weird one! I could reproduce it for a moment but not anymore... Don't know what's going on here.

**Comment by lionel-** [comment] 2015-10-08 09:01
> Don't know what's going on here.

No I got it. It's indenting relative to `function()` and not to `{`. I don't remember the reason behind this choice but it's not really a bug since `{` is supposed to be indented with `function()` as well.

If we add a tweak to get the behaviour (1) it'll need to follow the `{` though.

**Comment by lionel-** [comment] 2015-10-08 09:05
> any hint on forcing a correct display ?

The markdown syntax of Github is not the same one as stackexchange. You need code fences instead of 4 spaces. I edited your post with the correct formatting.

**Comment by lionel-** [comment] 2015-10-08 09:27
(2) is fixed in https://github.com/emacs-ess/ESS/commit/5cd5a4e53c1847b7f0c0e7738775532ca7ce9f03

**Comment by vspinu** [comment] 2015-10-08 09:33
We discussed (1) and I though that, Martin, you completely agreed back then. The main idea is that we don't want to re-indent the whole block based on whether { is on a new line or at the end of line (my post [here](https://github.com/emacs-ess/ESS/pull/227#issuecomment-135082795) and your answer following).  We really would like to avoid adding new exceptions, especially for such a small tweak.

If you want { to be on column 0 place your function on the same line with `<-`

```
splineDesign <- function(knots, x, ord = 4, derivs = integer(nx), outer.ok = FALSE,
                         sparse = FALSE)
{
    if((nk <- length(knots <- as.numeric(knots))) <= 0)
      stop("bla")
 
```

I think it's a good tradeoff. No need for to break our consistent settings with a new ugly exception.

**Comment by lionel-** [comment] 2015-10-08 09:39
I think the idea behind Martyn's pattern is that if you have a long function name it's not convenient to have the argument list within the 72 characters limit. So instead he breaks the function declaration on the next line, but still wants the body indented the same way.

> No need for to break our consistent settings with a new ugly exception.

I'd rather avoid a new exception as well but this style is featured all over the place in R core functions :/

**Comment by mmaechler** [comment] 2015-10-08 11:26
@lionel- :
- thanks for editing my code example and reminding me about the github markdown "limitation"
- yes exactly, you got my point: This is a very common exception  (which may even have been supported by ancient versions of ESS .. but I am less sure about that)

**Comment by lionel-** [comment] 2015-10-12 18:19
what about making `ess-indent-from-lhs` take either `nil`, a symbol or a list of symbols?

* Default would be `arguments`, as is the case now.
* It could also be set to `block-opening` or `(arguments block-opening)`

Additionally we could have `t` be equivalent to the full list so we have backward compatibility with 15.09, though I don't think we need to. Most probably no one changed the default and if they did, it's likely to set it to `nil` which poses no compatibility problem.

**Comment by vspinu** [comment] 2015-10-12 19:58
Can we just use the value of `ess-indent-from-lhs` for this? If it we do like Martin likes, if not we do it like as it is right now  

I personally don't mind either way of indenting `{`, both are good. I still think we should not have a separate config for it.

**Comment by lionel-** [comment] 2015-10-12 20:05
This would break RStudio indentation. While breaking blocks this way is not a common pattern, it occurs often enough that we should be able to follow both styles I think.

**Comment by vspinu** [comment] 2015-10-12 20:10
Ok. Then how about more general settings that would indent things generally to the left or right? So that if we have such dilemmas in the future we can reuse it.

**Comment by lionel-** [comment] 2015-10-12 21:37
hmm... In this case I think the lhs reference is more precise no? What other use cases do you have in mind for this left/right setting? It sounds really vague to me.

**Comment by vspinu** [comment] 2015-10-12 22:01
Indeed, you are right about lhs. That was the original idea behind that generic name :) 

Let's enhance that variable.  I like your proposal. But could you please make sure that naming is consistent with what we have with other variables. Do we have other collection-like options of this kind?

**Comment by mmaechler** [comment] 2015-10-14 14:56
I've got lost a bit about what you are discussing exactly above (several threads at once it seems to me).  There is still no fix to this problem, right?

**Comment by lionel-** [comment] 2015-10-18 15:37
> There is still no fix to this problem, right?

Not yet. Should I try to push a fix it for 15.09-1?

> Do we have other collection-like options of this kind?

We refer to `fun-decl` and `control-flow` in `ess-align-blocks`. In addition I propose the following nomenclature:

- `fun-decl` and `control-flow` (for loops and if/else branches) are both a kind of `prefixed-blocks`.
- `bare-blocks` and `prefixed-blocks` are both a kind of `blocks`, which is the most general collection.

Which degree of generality do we want here? Blocks, prefixed blocks or only function declaration?

With `blocks` we'd have the following indentation for bare blocks:
```r
object <-
{
    stuff
}

# instead of
object <-
    {
        stuff
    }
```

With `prefixed-blocks` we'd have this kind of things:
```r
object <-
    if (condition)
{
    stuff1
} else {
    stuff2
}
```

Personally I think we can start with accepting `arguments` and `fun-decl` and allow other kinds of blocks later if we ever have users requesting it.

**Comment by lionel-** [comment] 2015-10-18 15:43
And to finish the nomenclature, `defuns` is as general as `blocks` but includes in addition the innermost enclosing call and the LHS in case those exists.

**Comment by mmaechler** [comment] 2015-10-19 14:28
@lionel-

> > There is still no fix to this problem, right?
> 
> Not yet. Should I try to push a fix it for 15.09-1?

Yes, that would be pleasant.  Of course, I'm even more eagerly waiting for
@vsplinu's  handling of the slowness bug in #258 ..

**Comment by vspinu** [comment] 2015-10-19 18:16
> Personally I think we can start with accepting arguments and fun-decl and allow other kinds of blocks later if we ever have users requesting it.

Yes. Let's not complicate things unless necessary. 

>>    Not yet. Should I try to push a fix it for 15.09-1?
>Yes, that would be pleasant. 

I agree. We want to "solidify" new indentation as fast as we can.

>  'm even more eagerly waiting for @vspinu 's handling of the slowness bug in #258 ..

I was traveling and haven't had a chance to look at it as yet. Will do my best to fix it asap.

**Comment by lionel-** [comment] 2015-10-21 14:02
Martin, I'll try to get the indentation thing sorted out for tomorrow so we can release 15.09-1.

Two things:

* on further thought the symbol should be `fundecl-body` and not `fundecl`, because fundecl would refer to the whole function def.

* what default do we want? I think this indentation style should be optional but I have a feeling Martin would prefer it to be the default ;)

**Comment by mmaechler** [comment] 2015-10-21 20:11
Thank you for moving on, @lionel- .  I have no opinion about the naming (so I typically do prefer shorter to longer).... and yes, I would prefer it to be the default.... as it is used by many long-time programmeRs.  OTOH, I'm just one person in the ESS core team.. 
BTW: I'm not sure I will have time for release ESS 15.09-1 before the weekend (nor during).

**Comment by lionel-** [comment] 2015-10-22 14:35
here you go Martin

**Closed** 2015-10-22 14:35 UTC
