### ISSUE TITLE
`ess-insert-assign` not working interactively

### ISSUE THREAD

**Issue by SteveLane** [emacs-ess/ESS#760] opened 2018-11-20 20:45 UTC
I have the following to load ESS and map ";" to my assign key. It works fine in scripts, but does not work interactively (the old "_" did).

```r
(use-package ess
  :ensure t
  :ensure julia-mode
  :config
  (setq-default inferior-R-args "--no-restore-history --no-restore --no-save")
  (setq inferior-R-program-name "/usr/local/bin/R") 
  (setq ess-local-process-name "R")
  ;; Define new key
  (define-key ess-mode-map (kbd ";") 'ess-insert-assign)
  ;; Remove old '_' mapping
  (setq ess-smart-S-assign-key nil)
  )
```

ess-version: 18.10.2
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31

**Comment by lionel-** [comment] 2018-11-20 20:50
You need to bind in the inferior mode map as well:

```lisp
(define-key ess-mode-map (kbd ";") 'ess-insert-assign)
(define-key inferior-ess-mode-map (kbd ";") 'ess-insert-assign)
```

If you have many bindings to bind in both maps, you can loop over the maps this way:

```lisp
(dolist (map (list ess-mode-map inferior-ess-mode-map))
  (define-key map (kbd ";") 'ess-insert-assign))
```

**Comment by jabranham** [comment] 2018-11-20 20:52
Lionel's right and I just want to add the use-package-y way of doing this:

```
(use-package ess
  :bind
  (:map ess-mode-map
        (";" . ess-insert-assign))
  (:map inferior-ess-mode-map
        (";" . ess-insert-assign)))
```

**Comment by lionel-** [comment] 2018-11-20 20:54
This makes me think that one advantage of making ESS a minor mode is that we can share the same interaction map in the language modes and inferior modes.

**Comment by jabranham** [comment] 2018-11-20 20:55
Which may or may not be desirable. I've got different assignments in those maps:

```
  :bind
  (:map ess-mode-map
        ("M-=" . ess-cycle-assign)
        ("M-p" . my/add-pipe)
        ("C-|" . my/ess-eval-pipe-through-line))
  (:map inferior-ess-mode-map
        ("M-=" . ess-cycle-assign))
```

**Comment by SteveLane** [comment] 2018-11-20 20:58
Great, thanks. Sorry to ping with an issue.

On a related note, this is exactly the sort of thing that'd be great in a wiki as mentioned in #703 for example :)

**Comment by lionel-** [comment] 2018-11-20 21:03
> I've got different assignments in those maps:

Sure but we'll have the major mode maps available for the different assignments. Only the interaction map (or the relevant parts) would be shared. And users can move bindings from there to the major mode map.

**Comment by jabranham** [comment] 2018-11-20 21:05
Oh, right, of course.

**Comment by mmaechler** [comment] 2019-06-20 10:39
Somehow,  `ess-insert-assign` has stopped working for me ("interactively") again. Being an old timer, I have it assigned to `M--` both in inferior (i.e., `*R*`) and in R mode.  Where it continues working nicely in R scripts, it's not working (often at least) in inferior. I'm guessing this may be because `char` turns out to be `nil`  and so the whole `(and .....)` ends up to be exited early.

**Comment by mmaechler** [comment] 2019-06-20 10:44
(my guess about the *reason* for the problem is clearly wrong)
Note that the function definition itself has not changed recently (but in 2018-12),  but it may well be that the "non-working interactively" here has started back then... I need it much less than in R scripts, but still do want it for sure ...

**Comment by jabranham** [comment] 2019-07-01 13:46
Can you describe what "not working" means? Do you get an error or does - just get inserted literally?

**Comment by mmaechler** [comment] 2019-07-04 21:32
"not working" meant that it did not do anything (instead of inserting `" <- "`).  ... but I should have followed up.  That did happen in a `*R*` session, or in several... but it does not happen when I start emacs and ESS (and R ..)...  So, somehow I must have managed to break it *inadvertently*,  but it I think it did not happen again.  ... so this can be closed (as "nonreproducible") in a week or so, if nobody else (nor I) "stumbles" over this unpleasant phenomenon.

**Comment by jabranham** [comment] 2020-10-28 14:53
> so this can be closed (as "nonreproducible") in a week or so

I'm doing so now

**Closed by jabranham** 2020-10-28 14:53 UTC
