### ISSUE TITLE
[julia] support multiple workers in iESS julia

### ISSUE THREAD

**Issue by sam217pa** [emacs-ess/ESS#426] opened 2017-05-18 09:13 UTC
We can call julia on the terminal with `julia -p 4` to start julia with 4 workers (depending on the number of CPU on the computer) then call multi-threaded for loops.
Another way to specify that Julia should start with 4 workers is using `export JULIA_NUM_THREADS=4`. 

But when I do that in Emacs, `comint` throes an error and freezes for a while. 

Does anybody knows why it is like so ?

**Comment by izahn** [comment] 2017-05-18 21:20
I can't reproduce it here, using Emacs 26.0.50, ESS 16.10-1, and Julia
0.5.2 on Archlinux. What versions are you using, and on what OS?

Best,
Ista

**Comment by sam217pa** [comment] 2017-05-19 12:55
I am on OSX El Capitan, using Emacs 25.2.1 and ESS 16.10-1.
The output of `Threads.nthreads()` corresponds to the number of workers you defined in your setup ?

Thanks for having a look :)

**Comment by izahn** [comment] 2017-05-19 13:44
On Fri, May 19, 2017 at 8:55 AM, Sam217pa <notifications@github.com> wrote:
>
> I am on OSX El Capitan, using Emacs 25.2.1 and ESS 16.10-1.
> The output of Threads.nthreads() corresponds to the number of workers you defined in your setup ?

Yes, it does.

>
> Thanks for having a look :)

Sure. It might be helpful for you to verify that you can reproduce the
problem starting from 'emacs -q' and just loading ESS. That way we'll
know if there is something in your init file causing the problem.

Best,
Ista

**Comment by jabranham** [comment] 2018-09-18 22:40
Closing this as it seems to work just fine for me too.

**Closed by jabranham** 2018-09-18 22:40 UTC
Labels: lang:julia

**Comment by pmcvay** [comment] 2020-01-13 17:07
Is there a way to set the number of processors in the init file without environment variables?

**Comment by jabranham** [comment] 2020-01-15 01:56
Are you talking about using the `-p` flag? You can modify `inferior-julia-args` to do that if you want.
