### ISSUE TITLE
ESS hangs when opening R help

### ISSUE THREAD

**Issue by gavinsimpson** [emacs-ess/ESS#1095] opened 2021-01-17 23:02 UTC
I just upgraded to ESS version 20210117.1706. Having loaded {mgcv} via `library('mgcv')`, when I type `?gam` in a running R buffer I observe:

* the help page is not displayed (it is opened in a new buffer that I can switch to using the Buffer menu, but that buffer is no longer raised to be the visible buffer)
* I see the following in the Messages buffer:

        Retrieving RDS aliases...done
        ess-command: Timeout during background ESS command ‘names(formals(gam(formula,family=gaussian(),data=list))’

* the R prompt is not displayed (you can hit return in the R console buffer and the prompt displays).

This is with Emacs 27.1 (release 2.fc33 if that matters) on Fedora 33 with ESS version 20210117.1706. The version of {mgcv} is 1.8.33 (the latest CRAN release).

**Comment by lionel-** [comment] 2021-01-17 23:28
@r2evans Don't worry this is not caused by your fix that was merged today, I can reproduce with an older revision.

I think we are probably better off parsing these things from the R side instead of regexps on the elisp side.

**Comment by lionel-** [comment] 2021-01-17 23:30
Same as #1025.

**Comment by r2evans** [comment] 2021-01-19 15:42
@lionel- we had previously discussed (and @mmaechler commented, I believe) that switching to "R parsing" would be a next-major-version thing. Since the async stuff is both awesome *and* helping find other corner-cases/bugs, do you think that that discussion/change should be accelerated?

**Comment by lionel-** [comment] 2021-01-19 16:51
What do you mean by async stuff?

IIUC what I mean by "parsing" has a smaller scope than what you discussed with Martin. It's only about reimplementing `ess-r-help-usage-objects` on the R side, which shouldn't be too hard.

**Comment by r2evans** [comment] 2021-01-19 17:01
I think I blurred the lines between the `data.table::CJ` parsing and recent async efforts, sorry for the confusion. Please ignore that last comment.

**Comment by lionel-** [comment] 2021-01-19 17:21
Do you mean the improvements to `ess-command`? They are only related to the extent that they give us an informative and user-friendly timeout for this sort of hangs caused by incomplete inputs. Note that `ess-command` is synchronous rather than async. We'll have more async stuff in the future with #1017 but there hasn't been any changes on that front lately.

**Closed** 2021-01-26 11:19 UTC
Labels: bug, help, lang:r
