### ISSUE TITLE
ess-wait-for-process is called with TIMEOUT of 73.06 billion years

### ISSUE THREAD

**Issue by bryce-carson** [emacs-ess/ESS#1162] opened 2021-10-03 03:46 UTC
In my workflow I require `ess-remote` with R. I do experience issues with loading ess-remote into the remote process, which may be related, but can be left for another issue.

When interacting with Emacs and ESS, my Emacs will freeze up unpredictably when doing certain tasks:

- changing window
- moving point
- Using the spacemacs leader key
- executing code
- etc

It is quite difficult to describe the issue, I could record a video and narrate what I am doing, but it's pretty clear from the debugger info below that something is wrong. When my Emacs freezes I need to press C-g many, many times until I see a _fresh_ 'Quit' in the echo area. Then I can use evil-insert-mode again in another buffer, or simply navigate point, or regain control after changing windows (C-x o).

```lisp
Debugger entered--entering a function:
* symbol-overlay-refresh(1 5 0)
  accept-process-output(#<process shell> 0.3)
  ess-wait-for-process(#<process shell> nil nil nil 2305843009213693951)
  ess-command("getwd()\n" #<buffer  *ess-get-words*> sleep nil nil nil nil nil)
  ess-get-words-from-vector("getwd()\n")
  ess-synchronize-dirs()
  run-hooks(ess-idle-timer-functions)
  ess--idle-timer-function()
* apply(ess--idle-timer-function nil)
* timer-event-handler([t 0 1 0 repeat ess--idle-timer-function nil idle 0])
```

---

- GNU Emacs 27.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-08-07
- Spacemacs v.0.300.0
- ESS
    - Version: 20210924.1606
    - Commit: b1d299c96e73dc892b0065c1617205dd4b9f8ab8

As a sanity check, I have already re-cloned Spacemacs, re-installed all packages, and cleared caches, etc.

**Comment by lionel-** [comment] 2021-10-03 07:21
You can set `ess--command-default-timeout` to another value if you'd like but even a small value won't improve your experience a lot if ESS can't communicate with your remote properly.

You can also set `ess-can-eval-in-background` to `nil` to prevent background communication.

Closing this as duplicate of #1163.

**Closed by lionel-** 2021-10-03 07:21 UTC
